### ISSUE TITLE
picacomic cant download whole pages

### ISSUE THREAD

**Issue by i6omuHk** [tachiyomiorg/tachiyomi-extensions#10142]
### Source information

Picacomic 1.2.1

### Steps to reproduce

1.try download a comic which has 40+ pages

for example , a 100pages comic

### Expected behavior

download all 100 pages

### Actual behavior

only download front 40 pages

### Tachiyomi version

0.12.3

### Android version

Android 7

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [x] I will fill out all of the requested information in this form.

**Comment by lazureice** [comment]
It seems the author is @tarczf .
https://github.com/tachiyomiorg/tachiyomi-extensions/pull/9566
40 is the number of a page. Thus tachiyomi only download one page. 
[api1](https://github.com/AnkiKong/picacomic/blob/master/README.md#picture-%E6%BC%AB%E7%94%BB%E6%9C%AC%E4%BD%93)
[api2](https://github.com/abbeyokgo/PicaComic-Api/blob/master/README.MD#%E8%8E%B7%E5%8F%96%E6%9C%AC%E5%AD%90%E5%9B%BE%E7%89%87%E9%A1%B5%E4%BF%A1%E6%81%AF)

If you read a manga instead of downloading it, you can read all pages, so I don't know where the bug is.
