### ISSUE TITLE
webtoon69 keep opening webtoon18

### ISSUE THREAD

**Issue by arozaqf** [tachiyomiorg/tachiyomi-extensions#10373]
### Source information

webtoon69 1.2.15

### Steps to reproduce

1. open browse
2. sources
3. latest
4. it show error 404
5. open in webview and it show webtoon18 if you open in browser it show webtoon69 perfectly

### Expected behavior

it should open webtoon69 not webtoon18

### Actual behavior

open webtoon18 which is empty site

### Tachiyomi version

0.12.3

### Android version

android 8.1.0

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Deathray-II** [comment]
Just wanted to point out to whoever wants to solve this bug and rebuild the Mandra extensions so they're up to date with this: the generator is simply given the wrong URL:  [Here](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/01ecbdc8337681d9a943ca18bc05bf95f1baa7ab/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt#L418) you can see that for Webtoon69 it accidentally uses "https://webtoon18.com" instead of "https://webtoon69.com" and has been like that since it's creation in #8241 6 months ago but only surfaced recently with the removal of the hardcoded webtoon69.kt as of the merger of #10262
