### ISSUE TITLE
Ability to Read Paid Chapters in BiliBili Comics

### ISSUE THREAD

**Issue by Burakkurozu** [tachiyomiorg/tachiyomi-extensions#10586]
### Describe your suggested feature

Paid chapters should load into the extension if the reader in logged into their account.

### Other details

Just a potential future proofing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
I took a look into their API, and even when logged in and having "bought" a chapter (I just waited for the 1st tier 60s timer) they don't have any property in the chapter list of a given series that indicate if the chapter was bought by the user. 

So what can be done maybe is just showing all paid chapters if the user is logged in (through WebView, since they use cookies) and throw an error if the user didn't buy a chapter when trying to read. (The ideal would be just showing the free chapters + the ones that the user have paid). Authentication should be no problem, it's just an extra call to get the `credential` to be passed to the `ImageIndex` API endpoint.
