### ISSUE TITLE
ComicExtra: Searching in an individual extension generates a infinite loop

### ISSUE THREAD

**Issue by panoramix360** [tachiyomiorg/tachiyomi-extensions#10748]
### Source information

ComicExtra 1.2.10

### Steps to reproduce

1. Try to search for a word that has many titles with it
2. Scroll through the titles to reach the end
3. The next titles that will be loaded will be the same of the above and so on

### Expected behavior

I think that the correct way will be showing the next titles that fits the word searched (pagination or something)

### Actual behavior

Instead it shows the same titles that were previously shown.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Clydefrosch22** [comment]
This also happens when just looking at the "Latest" release and Browsing tabs,
It appears like it's simply parsing the same page over and over, right now, it displays Invincible first and Winx Club Comic last, which is exactly what's displayed on the first page of:
https://www.comicextra.com/popular-comic

Same with the Latest tab, it only seems to parse the first page of:
https://www.comicextra.com/comic-updates
Currently The Sandman Universe till Not Ninja HIgh School Special Edition

And that might be true for searches too.
The website uses a simple structure, just adding /2, 3, 4 etc. to jump to the next page.

A lot of people seem to avoid using this extension because it's harder to keep track of new releases in app on it, so I hope if this can be fixed, it might take some load off of the other two comic extensions, keeping everything alive a little longer.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
