### ISSUE TITLE
Manga-TR manga status isn't true

### ISSUE THREAD

**Issue by matmakif** [tachiyomiorg/tachiyomi-extensions#10804]
### Describe your suggested feature

There are two status in manga-tr.com first is "Publication" and second is "Translaction/Translation".
We see status in Tachiyomi from "Publication" so it's not true. It should be from "Translaction/Translation".
Please fix it. Thanks.

### Other details

Example image (it is completed in Kore but ongoing for Turkish)
![MangaTR](https://user-images.githubusercontent.com/59330357/153712283-6bb14b01-3734-4b8b-924b-e4adeed80419.jpg)
"Yayınlanma": "Publication"
"Çeviri Durumu": "Translaction/Translation"
"Tamamlandı": "Completed"
"Devam Ediyor": "Ongoing"

***
You can edit 55. line in [MangaTR.kt](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/multisrc/overrides/fmreader/mangatr/src/MangaTR.kt) for this to "manga.status = parseStatus(infoElement.select("div#tab1 table tr + tr td + td a").first().text())".
***

There are 4 status in Manga-TR.com: "Tamamlandı", "Devam Ediyor", "Çevirisi Bırakıldı" and "Çevirisi Yok". But there are only two status in Tachiyomi: "Ongoing", "Completed" and "Licensed". So it can be like this:
| Manga-TR | Tachiyomi |
|-|-|
| Tamamlandı | Completed |
| Devam Ediyor | Ongoing |
| Çevirisi Bırakıldı | Ongoing |
| Çevirisi Yok | Ongoing |

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
Hello, I'm trying to resolve this since you've suggested fairly minor changes, but I'd need you to check whether it's working correctly

You can download a test extension at this link expires in 24hours: [Link](https://wormhole.app/L8OKl#xBIAFPYY32KKnV8rUOPYvg)
Uninstall your current MangaTR extension
and install this new apk
go to More > Settings > Advanced > Clear Database and clear entries for Manga-tr
and then try opening/refreshing any manga from this source and see if the statuses are correct

in particular, you can check these random examples I've found:
 - [12 NIN NO YASASHII KOROSHIYA - LEO MURDER CASE (2009)](https://manga-tr.com/manga-12-nin-no-yasashii-koroshiya-leo-murder-case.html) which shows "Çeviri Durumu - Devam Ediyor" (Translation Status: In Progress)
 - and [A Kiss to my Prince](https://manga-tr.com/manga-a-kiss-to-my-prince.html) which shows "Çeviri Durumu - Tamamlandı" (Translation Status - Completed)

**Comment by matmakif** [comment]
Hello. I check, it looks like work correctly. Thanks.

**Comment by curche** [comment]
Nice. You may uninstall the extension now. The original mangatr extension will be updated
