### ISSUE TITLE
Mangahub's removal?

### ISSUE THREAD

**Issue by mengamenk** [tachiyomiorg/tachiyomi-extensions#10805]
### Source information

Mangahub 1.2.10

### Steps to reproduce

1. I update my library.
2. The update process took a long time.
3. Mangas from available extensions have update errors including Mangahub.

### Expected behavior

The update process should be working fine.

### Actual behavior

Instead, many errors occur.

### Tachiyomi version

0.13.1

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by OncePunchedMan** [comment]
MangaHub has been made obsolete due to the structure of the extension being changed. To resolve this, uninstall the obsolete extension and install the new one. No migration is necessary.

The extension name was changed from Mangahub to MangaHub so you must also change the name of your downloads folder to the new casing. Delete any extraneous extra folders with () in them if there are any.
