### ISSUE TITLE
Webcomics: Migrate to new endpoints

### ISSUE THREAD

**Issue by oswallt** [tachiyomiorg/tachiyomi-extensions#10959]
### Source information

Webcomics English 1.2.3

### Steps to reproduce

1. Load the Webcomics source extension.  "No results found"
2. Search for a title.  "No chapters found"

### Expected behavior

Show list of series.  Show list of chapters on the series page.

### Actual behavior

The main page shows "No results found."  You can search for a title, but the series page shows "No chapters found."

### Tachiyomi version

0.13.1

### Android version

Android 11

### Other details

The website has recently been updated so you can read all chapters without having to download their mobile app.  It looks the same, but maybe the structure has changed?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nattadasu** [comment]
This issue still occurred on extension version 1.3.3. Since the issue still open, I'll comment the bug here, unless the maintainers/contributors said otherwise. 

Tested on TachiyomiSY preview build version r463 (276d589b0, Jun 27, 2022 3:58 AM)

### Screenshot of issue:

![Screenshot_2022-07-07-04-58-31-640_eu.kanade.tachiyomi.sy.jpg](https://user-images.githubusercontent.com/49780229/177650721-a83d0bd5-a2c9-4aa6-9ad6-af6a8770d752.jpg)\
_SY source menu_

![Screenshot_2022-07-07-04-58-35-671_eu.kanade.tachiyomi.sy.jpg](https://user-images.githubusercontent.com/49780229/177650799-a314f8c3-4b11-4e69-b3f0-db2e58d3926a.jpg)\
_Latest modal_

![Screenshot_2022-07-07-04-59-13-832_eu.kanade.tachiyomi.sy.jpg](https://user-images.githubusercontent.com/49780229/177650862-da2585cb-96d5-4ca0-8e6b-fbd0b49f5fc9.jpg)\
_Search modal, shows broken result and invalid image cover_

![Screenshot_2022-07-07-04-59-18-820_com.webcomics.manga.jpg](https://user-images.githubusercontent.com/49780229/177651065-42c5fcbf-b6c6-4bfc-9e82-2d9f47548bf0.jpg)\
_Expected result for search query result, screenshot of main app_

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
