### ISSUE TITLE
Mangadex: search by author and scanlation team

### ISSUE THREAD

**Issue by dingleberry53** [tachiyomiorg/tachiyomi-extensions#10995]
### Describe your suggested feature

can this feature be added to the extension, I noticed that it finally got added to the mangadex website again.
like putting in the author or team name in the pull up menu thingy gives you their manga
thank you

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by CarlosEsco** [comment]
Unless something changes on the API end the best you can get is a UUID of the author, or UUID of the group search.   Tachiyomi main app doesn't support nested search with results.  i.e  Search author -> show list of results -> click result -> show list of manga

**Comment by dingleberry53** [comment]
oh okay thank you. a question tho how do you get the UUID? and does searching inside the extension with it gets you the results?

**Comment by curche** [comment]
You can find how to get UUID from *Section A. Finding the UUIDs* of the readme/guide [here](https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/all/mangadex#guides). 
Its just a 16 letter alphanumeric string. 
Eg: [https://mangadex.org/group/8ec5cc89-0828-4c8b-9b25-ed5bb83c43e9/jmanga-ex-licenses](https://mangadex.org/group/8ec5cc89-0828-4c8b-9b25-ed5bb83c43e9/jmanga-ex-licenses?tab=feed&page=22) -> 8ec5cc89-0828-4c8b-9b25-ed5bb83c43e9

If you have a group's UUID, you can search for their manga by just searching `grp:UUID`
Alternatively, if you're on a browser on phone (like Firefox), open the group's page on mangadex.org and use Open in App and open it in Tachi. 

A similar approach is available for Manga UUIDs ([`id:69598407-e128-4c8b-be43-feffa9fd98e8`](https://mangadex.org/title/69598407-e128-4c8b-be43-feffa9fd98e8/anaesthesiologist-hana)) and Chapter UUIDs ([`ch:1051123e-610a-4e2f-a9e5-219788211899`](https://mangadex.org/chapter/1051123e-610a-4e2f-a9e5-219788211899/1)). 

Since dex is still in beta stages, the best we can add is an Author UUID search that works similar to above

**Comment by dingleberry53** [comment]
wow thank you! that's super useful 
last thing you said would just do the trick if it does get added in the future
