### ISSUE TITLE
Madara: Deep linking broken

### ISSUE THREAD

**Issue by jopejoe1** [tachiyomiorg/tachiyomi-extensions#11142]
### Source information

Any Madara based Extension

### Steps to reproduce

1. Open Link from Madara based site in app
2. Wait

### Expected behavior

The manga associated with that url opens

### Actual behavior

It loads and never stops loading

### Tachiyomi version

r4197

### Android version

Android 10

### Other details

Is working in TachiyomiSY but fails in all other versions and forks of Tachiyomi

Partially Supersedes #10591

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
It fails because some sources uses other classes/HTML tags for the titles and other selectors that are used in the details parsing.

Probably the selectors needs to be updated to also include new and updated ones.

But, of course, something is missing in the app and an error should be thrown too instead of just loading forever.
