### ISSUE TITLE
Mangafreak error

### ISSUE THREAD

**Issue by bonfax4** [tachiyomiorg/tachiyomi-extensions#11196]
### Source information

Mangafreak

### Steps to reproduce

Try to update Kengan Omega  and table of demon gods.

### Expected behavior

Kengan Omega  and Table of demon gods having trouble updating, seems like the issue is in the syntax, letters in front of the  manga number, 149b and 369e.

### Actual behavior

Error while updating on these specific mangas.

### Tachiyomi version

0.13.1

### Android version

12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by elaitenstile** [comment]
Also experiencing this with Grand Blue's latest chapter release 75e. The issue seems to be [this line](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/1ca834b9deef4111414dcadde6babfd84409417d/src/en/mangafreak/src/eu/kanade/tachiyomi/extension/en/mangafreak/Mangafreak.kt#L125) which does not work if the chapter has a letter following the number.

**Comment by happywillow0** [comment]
This may have been fixed with #11244 with the update to the chapter number parser.
