### ISSUE TITLE
Webtoon TR: Chapter images do not load

### ISSUE THREAD

**Issue by Sterbenm** [tachiyomiorg/tachiyomi-extensions#11423]
### Source information

Wbtoon TR 1.2.20

### Steps to reproduce

when i reload any webtoon on Webtoon TR, it cant get episodes and then i open it in webview; i see that images dont loading.

### Expected behavior

getting episodes and monitoring images.

### Actual behavior

nothing btw

### Tachiyomi version

0.13.1

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
