### ISSUE TITLE
[Deletion Request] Delete Rit'i Scan

### ISSUE THREAD

**Issue by andersonp2050** [tachiyomiorg/tachiyomi-extensions#11480]
### Describe why this should be added

Source Websites
Name: Rit'i Scan
Link: https://riti-scan.com/
Language(s): Spanish

### Other details

I wish to have my page removed and deleted from this site. I have not given my consent to be added, we fight against gatherer pages and I see this. I'm disappointed.
Thanks.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.13.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by andersonp2050** [comment]
(https://github.com/tachiyomiorg/tachiyomi-extensions/issues/9286)

**Comment by alessandrojean** [comment]
First, we are not a site and **we don't host anything**. Tachiyomi is just a fancy internet browser. We also don't ask for any consent for sources to be added because it will be the same logic as Chrome/Firefox asking you permission to access your website.

The issue you linked is still open, which means there isn't any extension from your website created (yet).

That being said, if you still want an extension for your website not to be made you need to strictly follow the instructions provided in the "Source removal request" form instead, that are:

- Proof of ownership/intent to remove sent to a Tachiyomi Discord server mod via DM
- Site only hosts content scanlated by the group and not stolen from other scanlators or official releases (i.e., not an aggregator site)
- Site is not infested with user-hostile features (e.g., invasive or malicious ads)

Please request the removal and send the ownership proofs to an admin in [our Discord server](https://discord.gg/tachiyomi).

After that you can fill the "Source removal request" if the website is considered valid to be removed.
