### ISSUE TITLE
[Arabic] gmanga.me

### ISSUE THREAD

**Issue by yshalsager** [tachiyomiorg/tachiyomi-extensions#117]
(CATALOGUE) SOURCE REQUESTS:
Please Add Arabic Managa Site 
http://gmanga.me/

**Comment by Tsurayaka** [comment]
It will be so practical to read arabic manga is Tahiyomi :o

**Comment by wutwutwunderland** [comment]
I guess I'm just 28 days late.

**Comment by abidin24** [comment]
I hope that

**Comment by driwand** [comment]
when you're going to add an Arabic source?

**Comment by CarlosEsco** [comment]
@driwand nobody speaks arabic.  so you need to find a developer that wants to make the extension

**Comment by driwand** [comment]
@CarlosEsco I can help.

**Comment by as280093** [comment]
here are the logos 
https://github.com/as280093/TIcons/tree/master/Requested%20Extensions%20Icons/gmanga.me/res

**Comment by CarlosEsco** [comment]
Have to find someone that wants to develop it.  I dont have the time or desire to.

**Comment by katake3133** [comment]
Why you can't add Arabic source?

**Comment by CarlosEsco** [comment]
@katake3133  why can't you?

**Comment by katake3133** [comment]
I don't know how to add gmanga

**Comment by as280093** [comment]
Here the Icons
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/3615359/ic_launcher.5.zip)

**Comment by yshalsager** [comment]
@as280093 may you create icons for https://www.manga.ae too? I'll start adding Arabic manage websites and I've finished its extension.

**Comment by as280093** [comment]
> @as280093 may you create icons for https://www.manga.ae too? I'll start adding Arabic manga websites and I've finished its extension.

added in its issue request @yshalsager

**Comment by alsukaiti201** [comment]
@yashlsager Please add gmanga rather than manga.ae because gmanga is better

**Comment by yshalsager** [comment]
> @yashlsager Please add gmanga rather than manga.ae because gmanga is better

I've tried, but since gmanga is encrypting website HTML I won't be able to add it like ae.
I need to figure out how to decode website's HTML with its JS scripts first.
I'll give it another try later.

**Comment by hamaal94** [comment]
so there is no chance to add  gmanga  i tried mangaae but it wont work 
 so please consider er adding gmanga

**Comment by Amr-4** [comment]
Can you please adding gmanga.me rather tham manga.ae

**Comment by Manga-Killer** [comment]
> > @yashlsager Please add gmanga rather than manga.ae because gmanga is better
> 
> I've tried, but since gmanga is encrypting website HTML I won't be able to add it like ae.
> I need to figure out how to decode website's HTML with its JS scripts first.
> I'll give it another try later.

Gmanga's app source is closed
(No one can see or use it unless the owners)

**Comment by yshalsager** [comment]
@Manga-Killer well, but there's manga downloader script that supports it.
https://github.com/manga-py/manga-py
So there might be a way to get it working in Tachiyomi.

**Comment by Amr-4** [comment]
But manga.ae not worked, no chapters founded

في الثلاثاء، ٢٨ يناير، ٢٠٢٠ ٣:٠٨ م Youssif Shaaban Alsager <
notifications@github.com> كتب:

**Comment by Amr-4** [comment]
Manga.ae is not worked, no chapters founded

**Comment by mged** [comment]
please add gmanga

**Comment by AriaMoradi** [comment]
Looks like gmanga and gomanga both can be in the same multi source extension
Im Going to do some investigation and maybe come up with something

**Comment by AriaMoradi** [comment]
gmanaga is a ReactJS SPA
so the page has to be rendered first to add it as a source

**Comment by yshalsager** [comment]
> gmanaga is a ReactJS SPA
> so the page has to be rendered first then scraped

This might help https://github.com/manga-py/manga-py/blob/stable_1.x/manga_py/providers/mangago_me.py

**Comment by AriaMoradi** [comment]
@yshalsager 
does not work
```console
$ python manga.py "https://gmanga.me/mangas/344/sensei-to-watashi"
"WARNING:/manga_py/base_classes/base.py:103:2020-06-17 19:49:59,195:Chapters list empty. Check https://gmanga.me/mangas/344/sensei-to-watashi"
No new chapters found
```

**Comment by AriaMoradi** [comment]
some parts of the site are encrypted and opening them requires cracking the js code. and
1- doing that is really time consuming
2- any updates to the site might break the current code
3- as far as I know cracking their software is a no no

**Comment by AriaMoradi** [comment]
So the only way left is scraping the rendered site and as far I know the current technology stack only does dumb scrapings(no running of js code)

**Comment by AriaMoradi** [comment]
@SnakeDoc83 maybe add this too #3475 too?

**Comment by yshalsager** [comment]
@AriaMoradi weird, I remember it was working fine last time I used it some months ago.

**Comment by AriaMoradi** [comment]
updates can break third-party stuff at anytime

**Comment by SnakeDoc83** [comment]
@AriaMoradi 
If you want to take the time to crack their JS I'm not against it. As you mentioned, the source could change at any time and break your work but that's true to an extent with any extension. My point about not cracking an app mostly had to due with an old request I remembered where the user requested a source that was solely accessible through a closed-source app (so no website, accessible API, documentation, or anything to work with other than the app itself). In my opinion, that kind of request is unlikely to ever be filled by anyone.

**Comment by AriaMoradi** [comment]
A blend of react and webpack is not really nice, to crack the code you usually need to intercept HTTP request for the the main js file and replace it with your own (that has minifications removed and refactored names) to properly debug the code and gradually reverse engineer it. And now since I'm on linux now dont have the tools. (if anyone know freeware for this please mention)

Also this usually this leads to a game of cats and mouses where the vendor keeps changing their code if they are not fond of you doing this.
at least that's what I gather from csrf tokens and random encryptions on various parts.

**Comment by Samy-darker** [comment]
Is there any news about adding this awesome source :''(

**Comment by AriaMoradi** [comment]
@Samy-darker 
As any other open source project is gets done when someone takes the time to do it. This source has enough attraction already and as I said before its probably not easy that no one has done it. 
Anyways bumping it won't help. There are enough duplicate issues every now and then.

If someone finds another scraper/program that works on the site and is open source, I'm more that happy to do it myself.

**Comment by hayderalsal** [comment]
> Is there any news about adding this awesome source :''(

i think there is no hope to add gmanga

**Comment by AbdullahM0hamed** [comment]
*laughs in AZ webview magic*

**Comment by AriaMoradi** [comment]
how about setting up a bounty for it and interested users could donate to the hunt?

**Comment by clarencecastillo** [comment]
The following JS script successfully decrypts API responses. Haven't tried with all but it works well with manga chapters and search (and probably other encrypted APIs).

```js
const axios = require('axios');
const CryptoJS = require("crypto-js");

const response = axios.get('https://gmanga.me/api/mangas/1/releases')
response.then(res => {
  var enc = res.data.data.split('|')
  var message = CryptoJS.SHA256(enc[3]).toString()
  var jsonString = CryptoJS.AES.decrypt({
    ciphertext: CryptoJS.enc.Base64.parse(enc[0])
  }, CryptoJS.enc.Hex.parse(message), {
    iv: CryptoJS.enc.Base64.parse(enc[2])
  })
  return JSON.parse(CryptoJS.enc.Utf8.stringify(jsonString));
})
```

Any idea how we can run this from an extension? Or do we need to rewrite this in Kotlin?

**Comment by AriaMoradi** [comment]
> Any idea how we can run this from an extension? Or do we need to rewrite this in Kotlin?

Kotlin it is. The libraries you have access to do support sha256 and AES

**Comment by clarencecastillo** [comment]
The extension is now in a ready state, just need a few translations and testing for bugs. Preview can be downloaded from the PR #5274.

**Comment by clarencecastillo** [comment]
In case we need to do more cracking when they update this and also for future reference, thought I'd the steps I did to cracked the site's encryption mostly using my browser's dev tools:

1. From dev tools networking, observe that a `POST /search` is initiated when the [mangas page](https://gmanga.me/mangas) is opened and when a search is performed. We can also see that this request was done by an initiator `main_v96.js:1`. The `:1` suggests the script is minified which complicates things if we need to reverse engineer it, as you'll see in the next few steps.

![Screenshot 2020-12-30 at 19 07 50](https://user-images.githubusercontent.com/5035728/103347586-58e62f00-4ad2-11eb-82b3-69c94d5f5b2c.png)

2. If we look at the same request's response tab, we can see that the data is indeed encrypted. This confirms that our next step should be to reverse engineer `main_v96.js` since it's highly likely that the same script contains codes to decrypt it.

![Screenshot 2020-12-30 at 19 21 02](https://user-images.githubusercontent.com/5035728/103348187-3e14ba00-4ad4-11eb-80b8-6a5486d1b09c.png)

3. From dev tools debugger, find and open `main_v96.js` (if you don't see any files/folders, refresh the page). Here, we can confirm that the script is indeed minified, making it impossible to set debugging breakpoints.

![Screenshot 2020-12-30 at 19 29 10](https://user-images.githubusercontent.com/5035728/103348556-51745500-4ad5-11eb-913b-17f0f63a5bc7.png)

4. Fortunately, Chrome and Firefox debuggers (and probably most modern browsers), include a built-in unminify/prettify tool at the bottom bar of the debugger editor. More details [here](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Pretty-print_a_minified_file). Click that and should see the script unminfied. Notice that all variables become meaningless - a common step done by most minify and uglify tools.

![Screenshot 2020-12-30 at 19 34 18](https://user-images.githubusercontent.com/5035728/103348790-07d83a00-4ad6-11eb-9314-d1b53296b81b.png)

5. This part will probably take most of your time depending on how comfortable you are with debugging JS and how fast your machine is (due to repeated reloading and unminifying). Given the information we already know, I `cmd+f` for the string `/search` to find which line started the request. From there, we can set breakpoints to trace the actual function that performs the decryption.

![Screenshot 2020-12-30 at 19 40 25](https://user-images.githubusercontent.com/5035728/103349088-e3c92880-4ad6-11eb-8b2f-c39b1e0dc658.png)

6. My trace lead me to the following function which, when stepped over, transforms the argument `e` into an actual JSON object containing the good stuff.

![Screenshot 2020-12-30 at 19 50 44](https://user-images.githubusercontent.com/5035728/103349647-5ab2f100-4ad8-11eb-88e8-e5eff54d4325.png)

7. Next, I extracted this code and moved it to a controlled environment where I can experiment with it more. This is where I was at when I sent this:

> The following JS script successfully decrypts API responses. Haven't tried with all but it works well with manga chapters and search (and probably other encrypted APIs).
> 
> ```js
> const axios = require('axios');
> const CryptoJS = require("crypto-js");
> 
> const response = axios.get('https://gmanga.me/api/mangas/1/releases')
> response.then(res => {
>   var enc = res.data.data.split('|')
>   var message = CryptoJS.SHA256(enc[3]).toString()
>   var jsonString = CryptoJS.AES.decrypt({
>     ciphertext: CryptoJS.enc.Base64.parse(enc[0])
>   }, CryptoJS.enc.Hex.parse(message), {
>     iv: CryptoJS.enc.Base64.parse(enc[2])
>   })
>   return JSON.parse(CryptoJS.enc.Utf8.stringify(jsonString));
> })
> ```
> 
> Any idea how we can run this from an extension? Or do we need to rewrite this in Kotlin?

8. Lastly, we need a way to run this from an extension. As pointed out by @AriaMoradi, we can convert this to Kotlin since all the tools we need are available in the JDK. You can see the converted code [here](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/GmangaCryptoUtils.kt).
