### ISSUE TITLE
yeumanhua

### ISSUE THREAD

**Issue by yyzzuu** [tachiyomiorg/tachiyomi-extensions#11711]
### Source name

yeumanhua

### Source link

https://yeumanhua.com/

### Language

Vietnamese

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by vetleledaal** [comment]
Uses FMReader theme

**Comment by beerpiss** [comment]
Dead link

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
