### ISSUE TITLE
Bato.to: Covers does not load

### ISSUE THREAD

**Issue by BaoBunni** [tachiyomiorg/tachiyomi-extensions#12849]
### Source information and language

Bato.to, all 1.3.28

### Steps to reproduce

Example: 
Opens Bato.to extention
Shows no image on random Mangas
Shows signs of page break 
Unable to load image upon opening 

### Expected behavior

Shows images of manga art

### Actual behavior

Shows sign of page break

### Tachiyomi version

0.13.5

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by kikuKeii** [comment]
I don't know it helps you or not but it works for me, try clear database(Advance->Data->Clear Database).  
After updating the extension cover on bato it doesn't load but if you load it manually the cover is normal.  Because the cover that doesn't load is the cover we've ever opened without adding it to the library.
