### ISSUE TITLE
Animated glitched scans error 404

### ISSUE THREAD

**Issue by ecv03** [tachiyomiorg/tachiyomi-extensions#12865]
### Source information and language

Animated glitched scans 1.3.15(English)

### Steps to reproduce

It says Error 404 whenever I tap The said extension 

### Expected behavior

If i press the extension manhwa should show up

### Actual behavior

It showed error 404

### Tachiyomi version

0.13.5

### Android version

Android 12

### Other details

I already checked the webview and It works fine I hope it gets fixed, thank you!

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Xeiniac** [comment]
So I'm not 100% sure but I think the error is caused because they changed their links.

I'm assuming the extensions with this template use something like domainName/manga/ for the series and domainName/manga/?order=update for the latest

Animated Glitched Scans have renamed the manga page to series which also changes the link so instead of https://anigliscans.com/manga/ (like the other sites) it is https://anigliscans.com/series/

Similarly instead of https://anigliscans.com/manga/?order=update it is https://anigliscans.com/series/?order=update for the latest page

Well if this isn't the issue then idk 👀
