### ISSUE TITLE
mangasee deeplink bugged

### ISSUE THREAD

**Issue by zinklog2** [tachiyomiorg/tachiyomi-extensions#12958]
### Source information and language

Mangasee 1.3 33 English

### Steps to reproduce

Add any manga to library
Try to download it

### Expected behavior

Manga would start downloading 

### Actual behavior

Throws an error that starts with
Unexpected json offset at 14
Expected EOF at end of line but instead 

### Tachiyomi version

Tachij2k v1.5.6

### Android version

11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
What manga and chapter?

**Comment by zinklog2** [comment]
> 

All manga for me.  But just as an example vagabond chapters

**Comment by zinklog2** [comment]
![Uploading Screenshot_20220813-142937_Settings.jpg…]()

**Comment by zinklog2** [comment]
Wait actually after some experimenting I found out that this only happens if the manga I added was fromclicking on an external mangasee link which opened in tachiyomi.
If the manga was added manually through tachiyomi itself then it works as intended.

**Comment by zinklog2** [comment]
On a side note, If I add manga from an external link while that title was already in my library, it creates two copies of the same manga from the same source. This only happens with mangasee extension as far as I can tell.

**Comment by Seishirou101** [comment]
Yep seems like it

**Comment by scb261** [comment]
I didn't build and test it (and not planning), but I'm pretty sure that the issue is in lines 27 and 31 - need to remove the trailing `/` from the URL. It should at least solve the issue of having 2 of the same manga.

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/3a4982defd1f33e6841d0dcd90420d371a41d71c/multisrc/overrides/nepnep/mangasee/src/MangaSee.kt#L27-L31

And here is the line where the `/` from above affects chapter URL (no need to change anything here):

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/3a4982defd1f33e6841d0dcd90420d371a41d71c/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nepnep/NepNep.kt#L308

Don't want to create a PR w/o testing it, so I will leave it to someone else
