### ISSUE TITLE
MangaDex chapters marked unread

### ISSUE THREAD

**Issue by DJLevel3** [tachiyomiorg/tachiyomi-extensions#13622]
### Source information and language

MangaDex 1.3.168

### Steps to reproduce

What happened to me:
1. Open Tachiyomi for the first time in ~6 hours
2. See lots of manga with unread chapters
3. Open manga to find that the chapters are months old
4. Bugged chapters marked read remain read, unlike error in #13603 

### Expected behavior

Chapters that are read should stay unread 

### Actual behavior

Some chapters marked unread

### Tachiyomi version

0.13.6

### Android version

Android 13

### Other details

I will repeat this from earlier, this is a distinct issue from #13603 because the chapters do not mark themselves unread when refreshing.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
From Tachiyomi Discord #status-updates channel:
> For user that have entries from **MangaDex** that updated their libraries between 2AM UTC and 5AM UTC, restore a recent backup to mark all already read chapters as read again

**Comment by DJLevel3** [comment]
Already restored a backup, is this a known issue? If so, do we know why it
happens?

**Comment by alessandrojean** [comment]
Dex had instabilities that caused all chapters to being unindexed, so when Tachi refreshed the entry, there we're no chapters. When you refreshed again, the same chapters were indexed again but Tachi seems them as new since there weren't any chapters for a period of time.

Not really something we can fix as it was a Dex issue. The only fix is restoring a backup from before that happened if you have one, otherwise just mark everything you have already read as read.

Closing as there nothing to be fixed on the extension side.
