### ISSUE TITLE
UltraLight Scans

### ISSUE THREAD

**Issue by HappyPurple909** [tachiyomiorg/tachiyomi-extensions#13780]
### Source name

UltraLight Scans

### Source link

https://readlight.org/

### Language

English

### Other details

Formerly used Madera wordpress theme before site shutdown earlier in the year. Site has been restarted using the Bakkin reader/framework. reader logo:
![favicon](https://user-images.githubusercontent.com/17213259/194740604-e6c78b05-2db6-4727-ae28-b6e84f793f50.png) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by curche** [comment]
FYI, since this is a Bakkin theme without much modifications, you can already use it in Tachiyomi using the [Bakkin Selfhosted](https://tachiyomi.org/extensions/#en.bakkinselfhosted) extension: 
Just install that extension, go to Browse > Sources > Bakkin Selfhosted > :gear: > in Custom URL, enter this webstie and force close the app and open the Bakkin Selfhosted source

It can be made into a separate extension as well except the icon will need to be available in more sizes
In case you have a higher res version of the icon, please use the [Icon Generator](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html) or [Icon Kitchen](https://icon.kitchen/) to create all the required icons
Else, I can just use this and create the icons
