### ISSUE TITLE
Reaper Scan: Does not automatically update manga chapters and covers

### ISSUE THREAD

**Issue by MicOliv** [tachiyomiorg/tachiyomi-extensions#13833]
### Source information and language

Reaper Scan 1.3.36 (Brasil)

### Steps to reproduce

click on extension

### Expected behavior

the covers would load normally

### Actual behavior

the covers don't load but if you click on the manga they load 

### Tachiyomi version

TachiyomiJ2K 1.5.9

### Android version

Android 11

### Other details

besides the covers don't load, recent chapters only appear if you reload the manga itself, if you try to do it through the library they don't update 
![Screenshot_20221012-164221_TachiyomiJ2K](https://user-images.githubusercontent.com/106123470/195433584-4231fc84-0737-4239-bcc1-2939a190fab5.jpg)
![Screenshot_20221012-164031_TachiyomiJ2K](https://user-images.githubusercontent.com/106123470/195433590-435ac0d8-ebe6-4509-8325-9709014ec74c.jpg)
![Screenshot_20221012-164024_TachiyomiJ2K](https://user-images.githubusercontent.com/106123470/195433594-d245fdd4-9675-4d40-9e6a-7e1aacc18800.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Dragoon91786** [comment]
I've also noticed that loading the Reaper Scans catalog in the Browse menu is consistently quickly followed by the app crashing, specifically, latest nightly builds (last two versions).

**Comment by MicOliv** [comment]
now have this problem 
![Screenshot_20221015-111950_TachiyomiJ2K](https://user-images.githubusercontent.com/106123470/195991514-f53977e9-514a-4780-b5e9-5798efef8eb2.jpg)

**Comment by alessandrojean** [comment]
> recent chapters only appear if you reload the manga itself, if you try to do it through the library they don't update

Expected to happen as they're changing the manga URLs every new chapter they release. The extension tries to circumvent that, but it will not work every time, you will still need to migrate manually sometimes. Nothing really we can do about it, use other sources that don't have this bad behaviour if you wouldn't like to keep migrating eventually.

**Comment by alessandrojean** [comment]
@Dragoon91786 Please open a new issue filling all the requested information and **do provide the crash logs** there.

**Comment by Dragoon91786** [comment]
> @Dragoon91786 Please open a new issue filling all the requested information and **do provide the crash logs** there. I am not able to reproduce though, working fine on Preview and Stable.

Thanks, @alessandrojean for attempting to replicate the issue!

At the moment, I'm waiting for the app to fully load after I installed the latest preview. I sometimes find that after an update, it can take quite a while to load for the first time. Though, I can't say how much that is due to my device being extremely low on free storage for scratch & the general slowdown, the requirements of restarting several times to force TRIM, the excessively large index in Tachiyomi (see below👇🏽), or something else.

After the latest update, Stable doesn't seem to be crashing (so far). I'll double check in a bit & will get back to you if it is when if I end up needed to post a new issue like you suggested here.

> *@alessandrojea, Would it be helpful if I also include a ** system trace**, **ADB Debugging from my attached Workstation PC**, video screenshots of the crash (assuming it still occurs), or something else not specified here?*

I've been noticing the app won't record errors in the crash log for various things it does, and instead will simply close out/freeze, or will hang and I'll get the "Tachiyomi is not responding" pop-up with the [Wait] & [Close App] options. This particularly happens when I run database updates (at this point, there around 6,600 comics that update as part of that [far fewer than what I had previously, BTW; trying to keep it on only the stuff I actually have been reading or have in active circulation. 😅] update. When I do, Tachiyomi preview (sometimes even Stable does this, though since it has far fewer comics, it subsequently doesn't freeze up anywhere near as badly before it will actually engage the database update process). This has gone on for *quite* awhile now.

Tachiyomi Preview had errors/freezes/crashes (the app simply closes, particularly, if I turn off my screen & don't actively push [Wait] on the Android pop-up dialog boxes) that don't seem to post/recorded in the crash logs, even when they are set to verbose logging. Typically, the app will just spontaneously close for no specified reason. Sometimes I'll get the "Tachiyomi has stopped working and needs to close" or it will tell me that it has failed the backup attempts, which typically takes forever only to error out. In most of these cases, the crashes (such as the backup crashes I've had off-and-on, or backup fails, or the app will just close with no error message or dialog box), nothing gets reported in the crash logs.

I've started to wonder if these errors may be partly be due to how monsterously I overload the app with the shear magnitude of my library. My library likely exceeds 37,000 individual entries—probably in the 40k+ range.

That includes comics from expired extensions whose scanlation sites got closed along with a BUNCH of MangaDex comics that I have yet to fully migrate again due to the website URL changes due to the site hacking.

I figured that all of this strain, even on the hardware on my LG V60, probably pushes the app to its limits (and then some).

Out of curiosity, is the app built to fully utilize the larger memory of the slew of newer 64-bit devices? The way the crashes seem to happen, it's weird because they so often don't post a crash log. It acts like I just closed the app, but without explanation. Heh. 

Given these strange tendencies, are there any other diagnostics/debugging/reports that you'd like me to run and submit in my bug report in conjunction with those typically requested? Please, let me know and I'll get right on it! :3

I'll run whatever you want from system traces, record screen capture video of what happens, crash logs, and if needed, hook my phone up to my workstation and run whatever you need via adb debugging. :3 Just let me know!

Also, THANK YOU for all of your hard work (along with the other devs) designing, testing, and debugging Tachiyomi & its extensions! ❤️💯💯💯

**Comment by alessandrojean** [comment]
> I sometimes find that after an update, it can take quite a while to load for the first time

This is expected as since they're changing their series URLs every time, the source has to fetch all their titles first to be able to transform the old URL saved in your library to the most updated version one. It's the only solution available, as we can't guess their new URL for a particular series.

>  Would it be helpful if I also include a system trace, ADB Debugging from my attached Workstation PC, video screenshots of the crash (assuming it still occurs), or something else not specified here?

Yes, please do provide these in a new issue if it ever happens again.

> at this point, there around 6,600 comics that update as part of that

Please **do not do that**, you're seriously causing a lot of load to all the sources you use, leading more sites to start blocking their extensions. You **don't** need to update everything you have in your library. Configure update restrictions and only update what you're caught up on reading, there's no need to keep updating completed works (as an example).

> I've started to wonder if these errors may be partly be due to how monsterously I overload the app with the shear magnitude of my library. My library likely exceeds 37,000 individual entries—probably in the 40k+ range.

Definitely that, the app isn't designed to handle a big library like that, stop saving everything you see.

> Given these strange tendencies, are there any other diagnostics/debugging/reports that you'd like me to run and submit in my bug report in conjunction with those typically requested?

There's really not much we can do, as I explained before, the app isn't designed to handle a huge library like the one you have. Consider cleaning it and removing everything you are not really reading or will never read again. If you need additional help about the app, consider opening an issue in the app repository instead or asking for help on the #support channel on the Tachiyomi's [official Discord server](https://discord.gg/tachiyomi).

**Comment by Dragoon91786** [comment]
> > I sometimes find that after an update, it can take quite a while to load for the first time
> 
> This is expected as since they're changing their series URLs every time, the source has to fetch all their titles first to be able to transform the old URL saved in your library to the most updated version one. It's the only solution available, as we can't guess their new URL for a particular series.
> 
> >  Would it be helpful if I also include a system trace, ADB Debugging from my attached Workstation PC, video screenshots of the crash (assuming it still occurs), or something else not specified here?
> 
> Yes, please do provide these in a new issue if it ever happens again.
> 
> > at this point, there around 6,600 comics that update as part of that
> 
> Please **do not do that**, you're seriously causing a lot of load to all the sources you use, leading more sites to start blocking their extensions. You **don't** need to update everything you have in your library. Configure update restrictions and only update what you're caught up on reading, there's no need to keep updating completed works (as an example).
> 
> > I've started to wonder if these errors may be partly be due to how monsterously I overload the app with the shear magnitude of my library. My library likely exceeds 37,000 individual entries—probably in the 40k+ range.
> 
> Definitely that, the app isn't designed to handle a big library like that, stop saving everything you see.
> 
> > Given these strange tendencies, are there any other diagnostics/debugging/reports that you'd like me to run and submit in my bug report in conjunction with those typically requested?
> 
> There's really not much we can do, as I explained before, the app isn't designed to handle a huge library like the one you have. Consider cleaning it and removing everything you are not really reading or will never read again. If you need additional help about the app, consider opening an issue in the app repository instead or asking for help on the #support channel on the Tachiyomi's [official Discord server](https://discord.gg/tachiyomi).

Thanks, @alessandrojean again for getting back to me on this! :3

Ironically, I actually do have a bunch of restrictions set. 😅 Those are for the comics that I read, and it only updates every so often. 😅🤦🏽‍♂️ Before I figured out how to setup the restrictions (and after the "don't do huge updates because it strains the servers" message was introduced) it used to be FAR larger… 🤦🏽‍♂️

Thanks for answering my questions.

Ironically, most of the saves are for a particular site that I help host content for, and I use the app to keep track of seeding content vs stuff to be queued later.

That update number was actually for my current reading queue! 🤦🏽‍♂️ I read a ***lot*** of series… 🤦🏽‍♂️ #DisabilityLife 🤦🏽‍♂️

But, in any event, I'll spend some time later to make sure all of the completed comics gets weed out. I may need to switch things up and create a new filtering update scheme. I just wish I could set updating schedules for different parts of my library for different times. 😅 But… such is life.

I'll go ahead & do a full set of diagnostics if it happens again & post accordingly!

Thanks for letting me know though that my suspicions were probably correct, namely — the app is probably running out of memory or being highly strained by the way I use it. 😅 That helps a lot! :3
