### ISSUE TITLE
Doujindesu: Chapter images does not load

### ISSUE THREAD

**Issue by Andreaslur** [tachiyomiorg/tachiyomi-extensions#14004]
### Source information and language

Doujindesu 1.3.3/Indonesian

### Steps to reproduce

1) open the doujindesu extension 
2) select a comic 
3) open the chapter 
4) no image found

### Expected behavior

Please fix the doujindesu extension 
The image doesn't appear in the chapter

### Actual behavior

Image not found
![Screenshot_2022-10-28-01-36-19-01_afd66b7916d19a60815f56273408b73e](https://user-images.githubusercontent.com/116837873/198373757-169e4d20-3be7-499e-859e-32c2b0a0f225.png)

### Tachiyomi version

0.13.2

### Android version

Android 9

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.13.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
Yup confirmed
Still checking the code

**Comment by TheKingTermux** [comment]
I think I know the problem.

There is nothing wrong with the code in this extension (to display the image) in the following image except for errors in some comics with missing comic chapters.
Like :
![Screenshot_2022-11-06-17-59-02-10_afd66b7916d19a60815f56273408b73e.jpg](https://user-images.githubusercontent.com/50316075/200166992-97a2bd0b-6860-4322-bd07-7521338dd612.jpg)

The error when displaying the image is in the image source itself (src source) which denies access to users using VPN which can be seen in the following image.
Proof :
![Screenshot_2022-11-06-18-00-25-56_4d38fce200f96aeac5e860e739312e76.jpg](https://user-images.githubusercontent.com/50316075/200167014-28accb5a-ea53-4e0a-b509-9422232db88c.jpg)

Yes, Indonesians who use this extension (including myself) will definitely not be able to use this extension without using a VPN / DoH (tachiyomi's default feature (I think it can't be used now because so many restrictions)) or an error will appear.  Therefore, Indonesians use a VPN to access this extension in order to read/download comics available on the Doujindesu website.
