### ISSUE TITLE
can not connect wnacg

### ISSUE THREAD

**Issue by ccsugar** [tachiyomiorg/tachiyomi-extensions#14237]
### Source information and language

wnacg 1.3.9

### Steps to reproduce

连接wnacg显示以下错误
SSL handshake aborted: ssl=0x71a7de2408: I/O error during system call, Connection reset by peer

### Expected behavior

本来应该连上

### Actual behavior

显示
SSL handshake aborted: ssl=0x71a7de2408: I/O error during system call, Connection reset by peer

### Tachiyomi version

0.14.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
this may have been temp issue, as this was 10 days ago, but I am able to visit the site and do things normally, however ssl handshake errors are generally your connection is blocking them, which is possible since this seems like a +18 site, possibly using doh or a vpn may help. If you need more help, you can ask in discord.
