### ISSUE TITLE
Mcreader.net name change

### ISSUE THREAD

**Issue by HeroSharma** [tachiyomiorg/tachiyomi-extensions#14613]
### Source information and language

mcreader.net 1.3.16(English)

### Steps to reproduce

 Mcreader.net domain changed to Mreader.co

### Expected behavior

Extension name should be Mreader

### Actual behavior

Extension name is Mcreader.net

### Tachiyomi version

0.14.2

### Android version

Android 10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.2](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by DchanN** [comment]
From pull request https://github.com/tachiyomiorg/tachiyomi-extensions/pull/13728 , section https://github.com/tachiyomiorg/tachiyomi-extensions/pull/13728/commits/57e7fcdd91be1482e6fe4bd634c13df56313db77

![Screenshot_20221220-225700679 (1)](https://user-images.githubusercontent.com/101858971/208698140-5c2dac6c-f7ce-48e5-968a-a16eb07c6dff.jpg)


It's intentional for downloaded manga before domain change don't get orphaned , because when extension name change, downloaded manga will get orpahaned unless you rename the folder match with extension name manually

Well I'm dont know if rename source download folder when a sources name is changed already implemented in stable release

**Comment by HeroSharma** [comment]
> From pull request #13728 , section [57e7fcd](https://github.com/tachiyomiorg/tachiyomi-extensions/commit/57e7fcdd91be1482e6fe4bd634c13df56313db77)
> 
> ![Screenshot_20221220-225700679 (1)](https://user-images.githubusercontent.com/101858971/208698140-5c2dac6c-f7ce-48e5-968a-a16eb07c6dff.jpg)
> 
> It's intentional for downloaded manga before domain change don't get orphaned , because when extension name change, downloaded manga will get orpahaned unless you rename the folder match with extension name manually
> 
> Well I'm dont know if rename source download folder when a sources name is changed already implemented in stable release

![IMG_20221220_224957](https://user-images.githubusercontent.com/114504347/208727419-e6680c64-388f-4f21-9a24-3bb8aa972e4a.jpg)
![IMG_20221220_225007](https://user-images.githubusercontent.com/114504347/208727433-c96fb6af-c8fa-44ce-9405-040f3d4b43d6.jpg)

As you can see in above picture someone complaint about mcreader.net is down and it showing the site is down while nobody keep in check mcreader.net changed to mreader because site checker do not redirects the link it shows the site is down and results in wrong info extension status

![IMG_20221220_225552](https://user-images.githubusercontent.com/114504347/208728670-e9e44578-fc7f-4438-aa83-76718453a8f5.jpg)
