### ISSUE TITLE
INKR

### ISSUE THREAD

**Issue by omodia** [tachiyomiorg/tachiyomi-extensions#15210]
### Source name

INKR

### Source link

https://comics.inkr.com/

### Language

English

### Other details

- Their old website is [OLD INKR](https://inkr.com/explore/Fantasy). Their new website is [NEW INKR](https://comics.inkr.com/).
- Will be redirected to the new website if the chapter page is reloaded or if the comic in opened in new tab.
- Paid content requires login feature.
- First 12 chapters are free and majority of the paid chapters can be accessed for 24 hours after reading that chapter, new user bonus.
- So please add support for the new website.

### [New INKR](https://comics.inkr.com/),
- The images here are masked with **/t.jpg** at the end of the image link. The image is 100 x 224.
- The next image is only loaded after scrolling down, then '**/t.jpg**' is changed to '**/p.jpg'**.
- It has a resolution of 850 x 1275 and of jpg format. Which is weird.

https://user-images.githubusercontent.com/116664905/215994364-14183f60-f47d-4277-b20f-4a0319579cad.mp4

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Won't be added again, read #14068. Use their own site or app instead.

**Comment by alessandrojean** [comment]
It's still paywalled anyway and since their old website is eventually redirecting to the new one we consider it's the same. Inkr caused a lot of issues and was removed multiple times, it's best if it remains like it's right now, use their site or app as they want their users to do it, we can't do anything if they don't provide a download feature in their site or app. Also providing login support and download of paid content from their website would be against their ToS.
