### ISSUE TITLE
Failed pass claudflare 

### ISSUE THREAD

**Issue by herm00** [tachiyomiorg/tachiyomi-extensions#15711]
### Source information and language

Nhentai (all)

### Steps to reproduce

![Screenshot_2023-03-14-11-43-54-749_eu kanade tachiyomi](https://user-images.githubusercontent.com/42423803/225058343-f09543dd-4228-4bf7-8d1f-db674d9d2cc2.jpg)
![Screenshot_2023-03-14-11-54-48-333_eu kanade tachiyomi](https://user-images.githubusercontent.com/42423803/225062469-44ad4dff-f6e8-4d54-ad5f-3ab85847990f.jpg)

### Expected behavior

Should open normaly

### Actual behavior

Fails to pass claudflare 

### Tachiyomi version

Stable 0.14.5

### Android version

Android 12

### Other details

At first the Troubleshooting Cuide was useful but now it only enters a loop of captcha solvin

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
https://tachiyomi.org/help/guides/troubleshooting/#solving-cloudflare-issues

**Comment by ChristianCiach** [comment]
@Seishirou101 None of these tips are helping. I've been using Tachiyomi for over a year and until now I was always able to circumvent the cloudflare protection by using the WebView and/or other ways described by the guide, but this is the first time that the cloudflare protection seems to be impossible to overcome. So closing this issue by linking to the guide is not appropriat, since the guide doesn't help.

**Comment by curche** [comment]
As the guide says

> If they don't work, migrate to other sources or wait until they lower their protection.

Over the past years, nothing has remained unchanged
The app is more popular than ever and more and more websites are relying on Cloudflare
Website tend to use cloudflare's services to actually defend against large scale attacks
Or to just block bots and downloaders and apps like tachi (with a large userbase) since their servers cannot handle it

Also as noted in https://github.com/tachiyomiorg/tachiyomi/issues/9210#issuecomment-1468628479

> We don't handle higher levels of Cloudflare protection, which flags bot-like traffic such as that from Tachiyomi.

Its just only going to get insanely harder when websites abuse Cloudflare protection.
Consider waiting patiently, diversifying across alternative sources, or torrenting or other means

**Comment by ChristianCiach** [comment]
@curche Thanks, that's fair enough! I'm just a bit afraid that there may come a time where cloudflare protected will stop working with Tachiyomi for good. I know that this is something that is close to impossible to properly handle from inside the app, so the devs have my full understanding.

**Comment by herm00** [comment]
Aight all I must do is wait. Still can read nhentai through Chrome tho. I just like Tachiyomi. Thanks everyone for reply
