### ISSUE TITLE
Mundo Hentai

### ISSUE THREAD

**Issue by RyomeSukuna** [tachiyomiorg/tachiyomi-extensions#15732]
### Source information and language

Mundo Hentai 1.4.5 (PT-BR)

### Steps to reproduce

No Tachiyomi está só mostrando 1 capítulo enquanto no site possui mais de 2 capítulo.

### Expected behavior

Deveria mostrar todos os capítulos!

### Actual behavior

Só mostra 1 capítulo independente se tem mais no site.

### Tachiyomi version

0.14.5

### Android version

10

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please do provide examples where this happens, otherwise it's difficult to reproduce, and fill the information requested properly, such as the steps to reproduce. Consider using English next time as well so more contributors can have access to your issue and potentially fix it, otherwise it will be locked to Portuguese speakers.

Closing as it lacks useful information.
