### ISSUE TITLE
Doujindesu Alternatif 

### ISSUE THREAD

**Issue by cyberhome404** [tachiyomiorg/tachiyomi-extensions#16038]
### Source name

Doujindesu unoriginal

### Source link

https://doujindesu.vip/

### Source language

INDONESIA 

### Other details

This is not the original doujindesu but other doujindesu alternatives

18+/NSFW = Yes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by TheKingTermux** [comment]
*[This Issue Can Be Closed Now]*

Well, maybe I'll explain again about the Doujindesu Alternative Website which is the same as denying access directly via the link in the image shown. As I have said from Issue #15614 there I explained that the same website that you sent via request has the same problem. I can't bypass it.

![Screenshot_2023-05-03-20-40-06-42.jpg](https://user-images.githubusercontent.com/50316075/235935029-0d8aa105-3518-4ab3-80ab-5e530d4b5a7a.jpg)

And this problem already exists in the `Doujindesu` extension itself because the `Doujindesu` website denies access using direct links `(HotLinks)`, therefore I decline your request, because I'm looking for a way to bypass cloudflare from the Doujindesu website.

Thank you for your attention
