### ISSUE TITLE
Add way to disable "show only manga entries" to extensions.

### ISSUE THREAD

**Issue by K3end0** [tachiyomiorg/tachiyomi-extensions#16062]
### Source name

FreeMangaTop, TopManhua, ManhuaFast

### Source language

English (but not relevant to feature request)

### Describe your suggested feature

(For reference, i raised this as an [issue first in the main repository](https://github.com/tachiyomiorg/tachiyomi/issues/9336) but Arkon informed me it is an extensions issue)

It seems a few sources have trouble with the "show only manga entires" filter when it is enabled by default. The example that highlighted the problem to me is [FreeMangaTop](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/16057) which i created an issue for since the source breaks with the filter on completely.

But further testing has demonstrated that the problem is pervasive and affects other 'low-quality' madara sources in varying degrees. By way of example I tested 5 other sources i use a lot and two sources "Top Manhua" and "ManhuaFast" suffer from the same problem but in a more limited form. The filter makes actual comic entries disappear on a random basis.

It is for this reason that i request the functionality to let users disable the "show only manga entries filter". I think it would work best implemented in the same way users can toggle Random Latest Agent and Custom User Agent in an individual extensions setting, and given to all extensions so users can disable it on a source by source basis if they find the filter does not work well with a given source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.5](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
This usually happens when the source is incorrectly marking the series as a video or pure text novel format (which Tachiyomi doesn't support, hence the filter), or it's using a modified or outdated Madara version. When this feature was added to Madara extensions, it was enabled by default because only a few sources suffers from this issue you described, and the sources at that time were opted-out from the feature.

Since only a few sources have this issue and its kinda rare to it to happen (we usually don't have many issues about it), I don't think it's worth at this moment to make it configurable, but I opted out the sources you reported from the feature in #16075. If this starts to happen more often, the filter could be revisited and made configurable per-source as you suggested.
