### ISSUE TITLE
IMHentai: add missing "Speechless" language

### ISSUE THREAD

**Issue by GingGong343** [tachiyomiorg/tachiyomi-extensions#16424]
### Source name

IMHentai

### Source language

English

### Describe your suggested feature

There are a lot of Images not shown when browsing this extension because the "Speechless" language was not added. This language is not easily accessible in the website and can be accessed by clicking the icon for it on the top left of a result, or by simply going to this link https://imhentai.xxx/language/speechless/ . I really hope that the "Speechless" Language will be included in the source.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

**Comment by Opi-Txm** [comment]
I'd like to work on this.

The problem here is probably that when you open the extension of this source, you have to choose one of the languages that automatically enables the filter of the language, that you can't deactivate in the app and the speechless gets filtered out. I would create a new "Multi" extension source that has no language filters activated from the beginning.
