### ISSUE TITLE
Nhentai cloudflare bypass failure 

### ISSUE THREAD

**Issue by D1o2c3** [tachiyomiorg/tachiyomi-extensions#17056]
### Source information

Nhentai 1.4.37

### Source language

English, All

### Steps to reproduce

1. Open nhentai
2. Open in webview
3. Perform cloudflare verification 

### Expected behavior

Website should be able to view after cloudflare bypass.

### Actual behavior

Loop of verification not able to bypass

### Tachiyomi version

O.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Seishirou101** [comment]
#17045

**Comment by Mtkmanjaro** [comment]
the problem is specific to tachiyomi, i don't know if it's a block from nhentai to tachiyomi or the extension is broken in some way, I'm currently using kotatsu app and I'm able to bypass nhentai cloud flare without any problems, maybe since the user base of tachiyomi is huge nhentai decide to block the access, just speculation.

**Comment by Mtkmanjaro** [comment]
> #17045

the problem is specific to tachiyomi, i don't know if it's a block from nhentai to tachiyomi or the extension is broken in some way, I'm currently using kotatsu app and I'm able to bypass nhentai cloud flare without any problems, maybe since the user base of tachiyomi is huge nhentai decide to block the access, just speculation.
