### ISSUE TITLE
Asura null pointer exception 

### ISSUE THREAD

**Issue by rafrifray** [tachiyomiorg/tachiyomi-extensions#17150]
### Source information

Asura 1.4.50

### Source language

English

### Steps to reproduce

1.if you update the manhwa from asura it will not update
2. The message nullpointerexception will pop up
3. And no chapter found will po out to

### Expected behavior

It shoul update

### Actual behavior

1.if you update the manhwa from asura it will not update
2. The message nullpointerexception will pop up
3. And no chapter found will po out to

### Tachiyomi version

0.14.6

### Android version

Android 11

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by solivagonism** [comment]
the issue also arises when trying to download chapters or just open one.

the download icon shows an exclamation mark and when opening a chapter, the message "no pages found" pops up.

i believe the problem comes from the fact that they changed their way of sorting mangas in urls. it went from **https://www.asurascans.com/manga/0223090894-swordmasters-youngest-son/** to **https://asura.gg/manga/0223090894-swordmasters-youngest-son/**. (as an example.)

**Comment by Programmer-0-0** [comment]
this issue has already been solved according to #17136

**Comment by rafrifray** [comment]
Thanks bro
