### ISSUE TITLE
Japscan Error "Les deux tentatives de désembrouillage ont échouées"

### ISSUE THREAD

**Issue by Gaara-desuna** [tachiyomiorg/tachiyomi-extensions#17296]
### Source information

Japscan 1.4.42

### Source language

French

### Steps to reproduce

1. Get scan from Japscan source
2. try to read chapter
3. An error appear after some seconds, and close the player
![1](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/138038947/0ec485c3-1816-49c9-85d3-494fc706efe8)

### Expected behavior

Open the chapter and read

### Actual behavior

When I open a chapter, the player opens then after a few seconds it closes with an error

### Tachiyomi version

0.14.6

### Android version

Android 13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by Rajh** [comment]
To decrypt the images we need 2 keys.

We try to get those keys from the obfuscated source code but its not easy. And each time the extension break it's because the way to retrieve those keys changed...

I modified the app to add an extension parameter to specify directly those 2 keys. But its manual, each time the keys change, i need to get them manually again.

**Comment by alessandrojean** [comment]
It's obvious they're in a cat and mouse game with the extension, better solution is removing the extension as they're always breaking it on purpose.

**Comment by hutigh** [comment]
> To decrypt the images we need 2 keys.
> 
> We try to get those keys from the obfuscated source code but its not easy. And each time the extension break it's because the way to retrieve those keys changed...
> 
> I modified the app to add an extension parameter to specify directly those 2 keys. But its manual, each time the keys change, i need to get them manually again.

Is there a way we can do it by ourself if you teach us how to ? And apply it by ourself in the app ? 
Or if you do this they'll see how you do it and then fix it ? 

This is the only good French source from tachiyomi this would be so sad if we can't use this amazing app anymore

**Comment by aboudiom59** [comment]
Damn that's a shame it's not as high quality as Sushi-scan but it is the french source with most amount of manga. Maybe the site could be contacted?

**Comment by DamienCvl** [comment]
I think Japscan website's proprietary would like people to go on Japscan directly, mostly because of ads income.

I know that you can donate for support and they reward you with a token to have free-ads access on a browser of your choice.

Maybe it's (only) a money problem here. It could be a good idea to ask Japscan proprietary if we can use those token in Tachiyomi to access their content.

Only user who have donated will have access but it will be only 5€ (or less?) for a lifetime access.

**Comment by alessandrojean** [comment]
Please don't involve the site owners in this dilemma, several tries were done with simillar greedy sites in the past and it only made things worst. As I said, migrate to better sources.

Locking the thread as it's starting to become off-topic.
