### ISSUE TITLE
Permitting extension indexing without download

### ISSUE THREAD

**Issue by yohanim** [tachiyomiorg/tachiyomi-extensions#17444]
### Describe why this should be added

Basic idea
* there are a number of sources that have been removed because the scan team spend a lot of time screwing with everything to refrain automatic download of chapter images.
* We could limit the features of some extension to only indexing/alerting of new chapters and still having to go to the site to actually see them.

It would still serve the idea of an easy index of followed series with fast and easy links if not showing or downloading in app for each of them.

What's your thoughts?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
Batch checking manga updates also puts a lot of stress onto the servers. If we allow this kind of extensions, the source website will scramble the chapter list pages, so we may run into cat-and-mouse games again. In fact, some websites are/were already scrambling their chapter list pages instead of/along with the image pages. They just don't want their website to have any visits from Tachi at all.

Besides, this will cause a lot of people complaining in the support channel and on GitHub.

**Comment by yohanim** [comment]
@stevenyomi ok, I was thinking of properly labeled index only (or check update only).
I hear the users tickets because they would not read.
I was thinking some of the scan groups would accept that stress if it helps having people go on their site to read chapter instead of only migrating to aggregators. (From my user point of view it can be a win-win but it needs discussion with groups explaining the potential increase of actual site/ad views, that also takes time from dev team)
