### ISSUE TITLE
Manually add a new extension 

### ISSUE THREAD

**Issue by AkiKilganon** [tachiyomiorg/tachiyomi-extensions#17504]
### Describe why this should be added

I have some favourite extensions that I really liked, but recently they got deleted for technical reasons, and I would like if the app has a new feature where I can manually add a new extension so that I can continue using my favourite ones again 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I will fill out all of the requested information in this form.

**Comment by stevenyomi** [comment]
If you have an extension APK file, you can always install it and use it in the app, but we provide no support.

If the extension was deleted because it was hard to maintain, it was already broken. To make it useable, you need to do very complicated analysis of the website and write code to fix it. There's no such simple thing as to "manually add a new extension".

**Comment by AkiKilganon** [comment]
Sorry for wasting your time ig

Vào 23:40, Th 7, 12 thg 8, 2023 stevenyomi ***@***.***> đã
viết:
