### ISSUE TITLE
Manga Demon: incorrect URL encoding, shows no chapters

### ISSUE THREAD

**Issue by largo0** [tachiyomiorg/tachiyomi-extensions#17834]
### Source information

Manga Demon 1.4.4

### Source language

English

### Steps to reproduce

Search for FFF-Class Trashero in the app and it will show as no chapters but its available on the site itself

This ones used in the app
https://manga-demon.org/manga/FFF%252DClass-Trashero-VA4

This one needs to be used instead
https://manga-demon.org/manga/FFF%25252DClass-Trashero-VA4

### Expected behavior

It should show the correct link to display the chapters 

### Actual behavior

It doesnt show the proper link therefore unable to view chapters

### Tachiyomi version

1.6.6 

### Android version

android 13

### Other details

Talked about in support channel discord by Largo (me) and curche.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.6](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by TrippaTepis** [comment]
I've found the link needed is identical to the link its getting, but for some reason if you go directly to that link the page doesn't load. It will only load if you navigate through the site to the page.

**Comment by vetleledaal** [comment]
/edit-title "Manga Demon: incorrect URL encoding, shows no chapters"

**Comment by Lu5ck** [comment]
I second this, extension not working.

**Comment by Rubensei** [comment]
The issue comes from the use of `path` getter in `setUrlWithoutDomain`. It is decoding the first `%25` to a `%`.

https://github.com/tachiyomiorg/tachiyomi/blob/36f1e0e47648ca8745ee5f80b54b432a82dc0edf/source-api/src/commonMain/kotlin/eu/kanade/tachiyomi/source/online/HttpSource.kt#L413-L427

Replacing with `rawPath` will fix it since `HttpUrl` should handle the non decoded urls without any issues.

However, there is another bigger issue since the source seems to be changing the names periodically, at the moment I'm writing, they are using `...-VA7` but `...-VA6` is still usable.
