### ISSUE TITLE
Manga swat changed their url

### ISSUE THREAD

**Issue by Black7dz** [tachiyomiorg/tachiyomi-extensions#18048]
### Source information

MangaSwat

### Source language

Arabic 

### Source new URL

https://stmanga.me

### Acknowledgements

- [X] I have updated all installed extensions.
- [X] I have opened WebView and checked that the source URL is not updated yet.
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by 7allom** [comment]
Also it redirects to the main menu

**Comment by T3MYA11** [comment]
i can't open a new issues because you did first. so let me add more information about the bug here. first you can change the url domain in the extension setting but after that you can't update new chapters of any manga it just doesn't appear. second there is more problems with showing latest manga and new add manga it just showing random mangas. third and last bug is that the global search doesn't working you have to open the extension and search .

**Comment by Black7dz** [comment]
.

**Comment by Black7dz** [comment]
Ok
