### ISSUE TITLE
Myreadingmanga not working

### ISSUE THREAD

**Issue by yasnil03** [tachiyomiorg/tachiyomi-extensions#19165]
### Source information

MyReadingManga 1.4.47

### Source language

Multi

### Steps to reproduce

1. Open for Secure Captcha
2. Search for recent update
3. Open recent chapter

### Expected behavior

After opening recent chapter should able to show how many page to read

### Actual behavior

However upon opening the recent chapter only one page and error that can't load the page
![Screenshot_2023-12-03-09-09-15-022_eu kanade tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/48662401/be8489fe-32da-4be5-b139-10160b26748f)

### Tachiyomi version

0.14.7

### Android version

Android 12

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by nattadasu** [comment]
Reproduceable issue with the OP, affected on manga released since approx. Nov 28.

* Plugin version: 1.4.47
* Client version: Tachiyomi Stable 0.14.7, Tachiyomi SY Preview r532
* Android: 12, MIUI 14.0.2

Looking at the source image of a manga selected randomly that released since the date, the image is formatted as WebP rather usual JPEG/PNG. I don't know if Tachiyomi accepts WebP as image format as I rarely encounter or didn't use WebP for my local manga collection, but if it is not, then I think we need to move this issue  to main app repo instead?

However, if it is supported, simply update the regex on this line in https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/all/myreadingmanga/src/eu/kanade/tachiyomi/extension/all/myreadingmanga/MyReadingManga.kt#L109C63 to `Regex("""\.(jpg|png|jpeg|webp)""")`.
