### ISSUE TITLE
New Source: Taiyō

### ISSUE THREAD

**Issue by Luscarvalho** [tachiyomiorg/tachiyomi-extensions#19458]
### Source name

Taiyō

### Source link

https://www.taiyo.moe/

### Source language

Português

### Acknowledgements

- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension is not on [the removed sources list](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/REMOVED_SOURCES.md).
- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I have written a meaningful title with the source name.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
They're using Next.js new SSR which prevents from getting all information about their API. It also turns the scrapping harder as they're using Tailwind CSS. Gonna close for now but can be reopened if they document their API or something like that.

**Comment by rd-xx** [comment]
Hi @alessandrojean, would you mind sharing what exactly is needed for Tachiyomi to work properly? Which API endpoints are we looking for here?

**Comment by alessandrojean** [comment]
You can take a look into the [MangaDex API](https://api.mangadex.org) for reference, but basically:

- Paginated list of popular/trending manga;
- Paginated list of latest updated manga by chapter uploaded (optional);
- Paginated search (can include filters such as sort, genres inclusion/exclusion etc, but these are optional);
- Get manga details from id or slug;
- Get all manga chapters from manga id or slug (can be paginated but if all are returned in one call it's better as the app doesn't support pagination in this part);
- Get chapter pages (images) from chapter id or slug.

If you're the developer of the site, we can consider including a custom Tachiyomi user-agent if you need to stuff like statistics as well, although we can remove at any moment if there's any intentional blocking based on UA by the site side. Also keep in mind the user base from the app is huge, so you may face server scaling issues (although we rate limit Brazilian extensions to 1 request per 2 seconds).

If you need any additional help or have any other questions, you can ping me at the #programming channel on our [Discord server](https://discord.gg/tachiyomi) as well, Portuguese or English is fine on this channel.

**Comment by rd-xx** [comment]
I am indeed the developer of Taiyō. I will work on this in the upcoming month. 

Thank you for your help.

**Comment by alessandrojean** [comment]
Feel free to open a new source request issue when it's done, preferably with a simple documentation/list of the endpoints and any other additional details if needed.
