### ISSUE TITLE
Manga Starz and MangaSpark and Mangalink and Mangalionz 

### ISSUE THREAD

**Issue by yemenihandsome** [tachiyomiorg/tachiyomi-extensions#19529]
### Source information

1.4....

### Source language

Arabic

### Steps to reproduce

Access to the source
Wait a while
to fail 

### Expected behavior

Suggestions and actions should appear

### Actual behavior

A failure error occurred
![Screenshot_٢٠٢٤٠١٠٢-٠٨٣٣١٢_Tachiyomi](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/144265316/77bb6e86-4845-4775-b300-157ed5f6a3ff)

### Tachiyomi version

0.14.7

### Android version

Android 12

### Other details

The solution to these problems is here   #18756

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.14.7](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
Please refer to the "Cloudflare" section in the [troubleshooting](https://tachiyomi.org/help/guides/troubleshooting/#cloudflare) guide linked at the acknowledgements section. As stated there, if none of the instructions there help, wait until they lower their protection or migrate to other sources. 

Also please open one issue per source next time for valid issues, otherwise it keeps difficult to track on what have been addressed and what not.
