### ISSUE TITLE
[Meta] Webtoons.com extension - Sort Option

### ISSUE THREAD

**Issue by hyPnOtICDo0g** [tachiyomiorg/tachiyomi-extensions#2395]
###  Why/Project's Benefit/Existing Problem
It'll be really helpful if a sort option is added, because I can't navigate between original WEBTOONS & the WEBTOONS made by the users. Like the webtoon app/website, I can select webtoons based on genres. Also, by logging into my account using web view, I must be able to view my subscriptions.

**Comment by E3FxGaming** [comment]
I started going through your feature request (up until the wish for genres - didn't look into logging in) and noticed a couple of things.
I'll note them here so someone else doesn't have to go through the same thought process:

- Webtoon differentiates between "Originals" (toons approved by Webtoon) and "Canvas" (where basically anyone can publish any toon as long as it follows the site rules)

**Originals**

- When we view all Originals we can differentiate between ongoing and completed webtoons

- We can also look for a specific genre and although it's not that easy, we can probably also differentiate between ongoing and completed webtoons by inspecting the content of an icon area

- For both the described cases above, we can sort the results by "Popularity", "Likes" and "Date"

- We can search for a Webtoon that is of the Original category. If we search for a keyword, we no longer have the option to do any sorting or any genre restriction - we just get the search results for that keyword. On the first search results page we get 15 results, on all subsequent pages we get up to 18 results. There is no way to fetch all in one go.

**Canvas**

- When we view "all" Canvas works, we only get the first 20 and would then have to make another website request to request the next 20...

- We can also look for a specific genre of Canvas works, with the same restriction that we get 20 results with each page. The Genres for Canvas works are **not the same** genres that Original works use. (keep this in mind when designing the filter)

- For both the described cases above, we can sort the results by "Popularity", "Likes" and "Date"

- We can search for a Webtoon that is of the Canvas category. If we search for a keyword, we no longer have the option to do any sorting or any genre restriction - we just get the search results for that keyword. On the first search results page we get 15 results, on all subsequent pages we get up to 18 results. There is no way to fetch all in one go.

That's all I could observe so far.

Here are a few personal thoughts about it:

- it may be worth it splitting the current Webtoon ParsedHttpSource class into two classes - one for the Originals and one for the Canvas. We can't make this differentiation with a filter option, because we also have different genre lists for each of them. I couldn't find a method to swap out parts of the filter components depending on what the user selects as one of the filter options.

- we have to either programmatically (don't really think that's currently possible) or verbally tell the user, that genre filter and sort options don't matter anymore when the user searches for a keyword

**Comment by hyPnOtiC-d00g** [comment]
![Screenshot_2020-03-15-08-40-24-475_com android chrome](https://user-images.githubusercontent.com/44530973/76694434-a9ea7b00-6698-11ea-9dce-abcdb49bd173.png)

This applies for the Canvas sort 👇
Well, fetching results by inspecting the icon area is one thing, instead can't I fetch the results of a genre by just clicking on the required one? (Screenshot for details)
Although each genre doesn't have it's own link, I'm able to get fetch results by clicking on it in a browser. I'm able to do this by clicking the ⬇ key in the canvas' home screen. I'm not experienced in kotlin so can't explain programmatically.

**Comment by hyPnOtiC-d00g** [comment]
Well, I looked at your comment and I want to add a few more things.

**Originals:**
- Sorting Ongoing & Completed Webtoons:

	
	Both have their own respective websites, so results can be fetched from them.
 
	Ongoing Webtoons: https://www.webtoons.com/en/dailySchedule#ongoing
	Completed Webtoons:  https://www.webtoons.com/en/dailySchedule#completed

	As you said, looking for a specific genre would be a hard task as there is also another sort option in the website to sort the results by "Popularity", "Likes" and "Date". So it'll become a double sort. It'll become too complicated as it would be hard to fetch results for Ex: "Most 'Popular 'Thriller' Webtoons in the 'ongoing/completed' series". 
Basically, navigating to ongoing/completed, sort by "Popularity", "Likes" or "Date", then fetching results for a specific genre is tricky. I get it now.

Default sort for originals is sort by popularity.

**Canvas:**

   

- As you said, We have to make multiple site requests to fetch results, I found out that, when we view 'All', until the 1000th page there is a page number icon at the bottom, and you can't view anymore Webtoons in the website after the 1000th page. But if I keep on incrementing the number 1001,1002...etc in the address bar it keeps on displaying new Webtoons until the page 3876, and after that if I continue incrementing, it keeps displaying the same results as the page 3876. As new webtoons are added, probably a page gets added. That's my theory. Results can be displayed by fetching results from each page and then incrementing the page number and make another website request.

https://www.webtoons.com/en/challenge/list?genreTab=ALL&sortOrder=UPDATE&page=3876
https://www.webtoons.com/en/challenge/list?genreTab=ALL&sortOrder=UPDATE&page=3877

Hypothetical Situation: If a user scrolls upto page 3876 or upto any page which shows same results as the previous one, then we've to end at the last page so that the app doesn't display duplicate results.

-  Looking for a specific genre is a simple task as each genre has its own website.

Ex:- Romance: https://www.webtoons.com/en/challenge/list?genreTab=ROMANCE&sortOrder=UPDATE

Only exception is the "Other" genre. It contains 14 sub genres. Instead of displaying the "Other" genre in the app, we can just display the 14 other ones by appending each genre's name to the end of the link. 
Ex:- Horror: https://www.webtoons.com/en/challenge/list?genreTab=ENGLISH_OTHERS&sortOrder=UPDATE&genre=HORROR 

Here, sorting results by "Popularity", "Likes" and "Date" is simple as each genre has its own website, and also just by changing the keywords in the link we can fetch and sort results at the same time.

Ex:- https://www.webtoons.com/en/challenge/list?genreTab=ROMANCE&sortOrder=UPDATE

Here, ROMANCE is the genre & UPDATE is the sort, which is sort by date. 
So, for the other two:
Popularity - READ_COUNT
Likes - LIKEIT

Also, if a user selects multiple genres, then results must be fetched from both websites, but I personally think this would be tricky because it isn't like websites like kissmanga etc which have their own advanced search option.

Default sort for canvas is sort by date.

- Login feature

I think that logging in feature is helpful for people who have huge subscriptions in their library, and it tough to migrate all of them into Tachiyomi. Instead by logging into their using web view, their subscriptions can viewed by fetching results from: https://www.webtoons.com/en/favorite

These are a few additions. Hope it helps.
