### ISSUE TITLE
[Bug] Russian Extensions Bugs Again

### ISSUE THREAD

**Issue by D3xron** [tachiyomiorg/tachiyomi-extensions#2548]
This is continue of my issue #2345 

Anibe - Failed to connect to api.anibe.ru/80.76.42.122:443
Onlinecomics - domain change to .ru right now is onlinecomics.ru

**Comment by SnakeDoc83** [comment]
There's nothing on anibe's site; so if it's been like that since your last post there's a good chance the site is dead.

AkaiYuhiMun is unreachable; so same thing here.

Onlinecomics can be changed.

Yes, bato.to, mangatensei, and mangawindow are basically the same.  We know and it's not a bug.

**Comment by D3xron** [comment]
Ty for answer, I hope this information help you! In Discord server I'm Dexroneum

**Comment by D3xron** [comment]
AkaiYuhiMun have a different website right now, Japit Comics this a new team name, and Yes this source added to your application, thanks “happywillow”

**Comment by D3xron** [comment]
Can you fix this?

**Comment by scb261** [comment]
Anibe - still down, I'll PR removal
onlinecomics.su - looks like it's just news about comics now, I'll PR removal as well
onlinecomics.ru - redirects to bazingacomics.ru that also has only news
AkaiYuhiMun - removed because it is down (#2586)
Japit Comics - removed because they don't have manga (#5089) and as I can see they have only novels now

If I'm wrong about something and it actually works and has comics/manga, please open separate issue for each site

**Comment by D3xron** [comment]
All correct, thank you!
