### ISSUE TITLE
Hiveworks Comics : Unsupported chapter list. 

### ISSUE THREAD

**Issue by joshynessism** [tachiyomiorg/tachiyomi-extensions#3153]
### Device information
* Tachiyomi version: 0.9.2-2289
* Android version: 8.0.0
* Device: ATU-L22

### Source information
* Source name: Hiveworks Comics
* Source extension version: 1.2.4

## Issue/Request
Unsupported chapter list.

## Other details
![Screenshot_20200515-015444](https://user-images.githubusercontent.com/50773030/81969337-612b5000-9650-11ea-803e-d597eb2346af.jpg)

**Comment by roshavagarga** [comment]
Can confirm, still an issue on the latest version of Tachiyomi and the plugin for me - specifically for the Dumbing of Age comic.

Is there any workaround to get the chapters? If not, @SnakeDoc83 - shouldn't this be tagged as a bug, rather than enhancement?

Sidenote: That string should use `an` instead of `a`.

**Comment by roblabla** [comment]
Girl Genius and Witchy also have this problem. I have a fix specialized for witchy in #7033 .

The underlying problem is that each of those present the page list in a custom fashion (or not at all). The "normal" way to get the list of pages/chapters (the hiveworks source currently don't make a distinction) is to get, for instance, https://www.sleeplessdomain.com/comic/archive, look for the `<select>` tag, and list all of its `<option>` (which should hopefully be one for each page). If the select tag skips some pages, those will also be skipped by the source... more on this later.

In contrast, SSSS instead has a bunch of links in https://sssscomic.com/?id=archive

Dumbing of Age has two archives, one that allows getting all pages (as a bag of links) for a single year (so we need to fetch this N times for each year) at https://www.dumbingofage.com/archive/, and another that allows getting chapters at https://www.dumbingofage.com/archive-2/ (only requires one fetch, but doesn't get all pages).

GirlGenius has a "scene" `<select>` in the comic page, each scene being a couple of pages long. Knowing how many pages is within a scene looks fairly complex. This doesn't work with the existing chapter list because it's not at the right location, but also it doesn't have one option per page, so we'd end up skipping half the pages anyways. 

I'll try to work on getting some of those working using site-specific hacks.

**Comment by roblabla** [comment]
Others that don't work, categorized by how we could fix them:

- There appears to be a software in somewhat wide use that has its archive at `/archives/`, and for which we could select pages with the following selector: ".comic-archive-title a".
  - The End: http://www.endcomic.com/archives/
  - Helvetica: http://helvetica.jnwiedle.com/archive/ that looks familiar. 
  - Manly guys doing manly things: https://thepunchlineismachismo.com/comic/archive
  
- Many websites seem to hide the select box we use to find the chapters, and instead only show a list of thumbnails.
  - Witchy: https://www.witchycomic.com/comic/archive (click on chapter 1)
  - Kochab: https://www.kochab-comic.com/comic/archive

- Others hide the chapter select box, and have a list of links instead of a list of thumbnails:
  - The Glass Scientists: https://www.theglassscientists.com/comic/archive
  - Bicycle Boy: https://www.bicycleboy.net/comic/archive

- Some websites have their archive at /archive instead of /comic/archive
  - Real Science Adventure: https://www.atomic-robo.com/rsa/archive

- Some websites don't work for unknown reasons yet (they follow the current pattern but still fails. Investigation needed):
  - Inside Phobia: Dunno why it doesn't work. Seems to follow the traditional structure.

- More websites seem to use something totally custom
  - Sam & Fuzzy: looks like a PITA. Has a custom chapter list @ https://www.samandfuzzy.com/archive. Can get all the pages with https://www.samandfuzzy.com/archive-date-range
  - Guilded Age: Custom chapter list at http://guildedage.net/archive/
  - Goblins: Custom chapter list at https://www.goblinscomic.com/comic/archive
  - Barbarous: This one's a mess, the website hosts two different webcomics plus random stuff. Barbarous' archive is http://www.johnnywander.com/comic/archive/storyline-23, it's a paginated page list.
  - Something Remarkable: Custom chapter list, `.chapterHeaderLink a`. https://sufficientlyremarkable.com/comic/chapters
  - No Need For Bushido: Custom page list, `a.webcomic-term-link` http://nn4b.com/story
  - Beeserker: `.archiveTitle a` http://www.beeserker.com/archives/full-archives/

**Comment by BruhMomient** [comment]
any chance of these issues getting fixed, considering how complex it seems and it not being a popular source?

**Comment by roshavagarga** [comment]
Still want this, please reopen :)

**Comment by laundmo** [comment]
Would really like some updates on this, trying to read Girl Genius on their own page is painful due to the layout requiring me to zoom in each time

**Comment by arkon** [comment]
In an effort to have a more manageable issue backlog, we're closing older requests that weren't addressed since there's a low chance of it being addressed if it hasn't already. If your request is still relevant, please [open a new request](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/new/choose).
