### ISSUE TITLE
[Bug] Manga Park: missing chapters

### ISSUE THREAD

**Issue by jfcaraujo** [tachiyomiorg/tachiyomi-extensions#4011]
### Device information
- Tachiyomi version: 0.10.3
- Android version: 9

### Source information
- Name: Manga Park
- Extension version: 1.2.17

## Steps to reproduce
1. Opened One piece 

### Expected behavior
Should show all the chapters

### Actual behavior
For the rock source, it's missing the chapters 701-786, even thought they show up in webview (note: I think there are other missing, that's just the most obvious I could find) 

### Additional information
In the website some chapters are unordered and it has chapter 787 between chapter 700 and 701, I think that may be the cause
![Screenshot_20200804_161608_eu kanade tachiyomi](https://user-images.githubusercontent.com/20336458/89315237-87222880-d672-11ea-9796-dc75f22e9537.jpg)
![Screenshot_20200804_161647_eu kanade tachiyomi](https://user-images.githubusercontent.com/20336458/89315266-8d180980-d672-11ea-9499-b8ec88c10efb.jpg)

**Comment by E3FxGaming** [comment]
Can't say I found a solution (especially not one that doesn't break chapter progress for all users so far), but I think I at least completely found out what the problem is.

Tachiyomi stores the chapter number as a Float. Float is a good data type for numbers with up to ~6 significant digits (this is simply a limitation of the amount of memory allocated for this data type in the background).

What the extension currently does is read the chapters from smallest (oldest?) to largest (newest?) and ideally all chapter numbers just follow one after another. If a chapter number is smaller than the chapter number which it read before the current one, the authors of this extension wanted the extension to increment the chapter number by 0.00001 for every chapter until a larger number is read, at which point the counting would resume normally.

So the plan was (with an example)

1. Read chapter 1 - that's Tachiyomi chapter number 1.0
2. Read chapter 5 - that's Tachiyomi chapter 5.0
3. Read chapter 2 - that's Tachiyomi chapter 5.00001
4. Read chapter 3 - that's Tachiyomi chapter 5.00002
5. Read chapter 4 - that's Tachiyomi chapter 5.00003
6. Read chapter 6 - that's Tachiyomi chapter 6.0
7. ...

There is a significant problem with this approach. I said earlier that Float is good for numbers with ~6 significant digits. Significant digits are all relevant digits to correctly re-represent a number (leading and trailing zeros are not significant digits, but all other digits, including those before the decimal point are significant digits).

The example I brought up barely works, because there are 6 significant digits at most. However manga like the One Piece shown in this post have more than 100 chapters.

So another example would look like (going by what is shown in the second screenshot)

1. Read chapter 694 (let's say it starts here) - that's Tachiyomi chapter 694.0
2. Read chapter 693 - that should be Tachiyomi chapter 694.00001
3. Read chapter 695 - that's Tachiyomi chapter 695.0
4. Read chapter 694 (again - as far as I can tell there are colored and non colored ones) - that should be Tachiyomi chapter 695.00001
5. Read chapter 696 - that's Tachiyomi chapter 696.0
6. ...

I already wrote "that should be and not "that's", because numbers like 694.00001 have 8 significant digits - too large to store in a Float, leading to unintended behavior due to floating point precision problems.

How to solve this? I don't have a solution. There are data types like BigDecimal, that can store (in theory) numbers as big as there is memory, however that's quite performance impacting. Or we could extension-internally use Double instead of Float (Double can handle up to ~16 significant digits accurately). Either way we would thereafter have to map our internal counting to the Float which Tachiyomi expects, and it would certainly not lead to the same chapter numbers that we have now, messing up the read progress for people that already use the extension.

**Comment by jfcaraujo** [comment]
This might be somewhat of a stupid question, but why keep that internal numeration? Why not just make:
1. oldest chapter
2. second oldest chapter
3. third oldest chapter
...

without caring for the numeration of that chapter? 
Or maybe adding 0.01 instead of adding 0.00001, since i doubt there are over 99999 repeated chapters ?
Or maybe even, for the example above, this?
Read chapter 1 - that's Tachiyomi chapter number 1.0
Read chapter 5 - that's Tachiyomi chapter 5.0
Read chapter 2 - that's Tachiyomi chapter 2.0
Read chapter 3 - that's Tachiyomi chapter 3.0
Read chapter 4 - that's Tachiyomi chapter 4.0
Read chapter 5 - that's Tachiyomi chapter 5.00001
Read chapter 6 - that's Tachiyomi chapter 6.0

**Comment by CrepeTF** [comment]
Also update your Tachiyomi to latest version 0.10.5

**Comment by jfcaraujo** [comment]
> Also update your Tachiyomi to latest version 0.10.5

It was the latest at the time, but I think the problem is with the extension, not the app itself
