### ISSUE TITLE
[English] TwoKinds

### ISSUE THREAD

**Issue by j2ghz** [tachiyomiorg/tachiyomi-extensions#457]
http://twokinds.keenspot.com/archive/ select `a[href^="/comic"]` for chapter links
http://twokinds.keenspot.com/comic/1/ select `img[alt="Comic Page"]` for image
If no one picks it up, I'll probably get to finishing it sometime.

**Comment by as280093** [comment]
Here the icons 
[TwoKinds.zip](https://github.com/inorichi/tachiyomi-extensions/files/3614935/TwoKinds.zip)

**Comment by Xeddius** [comment]
Can this be re-opened until there's actually a working Keenspot/Twokinds source?

**Comment by AMDHome** [comment]
So I took a look at this recently and came across a few things that make this somewhat difficult.

These issues are mostly due to how the comic's website is structured vs what Tachiyomi expects.

1. It's difficult to create a general Keenspot extension as the `First`, `Previous Page` and `Next Page` buttons are all coded slightly differently across the various series that are branded Keenspot. To the average person who goes to any webseries on a keenspot website, it looks more or less all the same, but the underlying HTML isn't consistent across the various webcomics. There are workarounds for this issue, but it will make everything kinda messy if we try to force a generalised extension to work with Tachiyomi.

Now if we decide we don't care about all of Keenspot and just want Twokinds, then this is not an issue. 

2. Unlike most manga series, Twokinds does not follow a chapter by chapter release. Tom Fischbach (Author of TwoKinds) releases individual pages. This causes an issue with the way Tachiyomi manages chapters.

    For all manga sites, they nicely group themselves into chapters, but TwoKinds doesn't really do this. I know I can go to [https://twokinds.keenspot.com/archive/](https://twokinds.keenspot.com/archive/) to find the chapters, but again, this archive page really isn't set up to Tachiyomi's expectations. Like before, there are workarounds for this issue, but it is very messy and very difficult to code for.

    Alternatively, We could do what the `Tapas` extension does and just make each page into its own "chapter" but since Twokinds is ongoing and currently has 1129 pages (as of writing), this webcomic would have would have 1129+ chapters. Plus, if you were to binge read this comic you would have to change chapters (swipe twice) every time for the next page. It would get kind of annoying. This is the easiest option, but results into a relatively poor user experience. I believe this was already tried and rejected in #1150

    A third option is to put all pages into one big chapter and just create another new bigger chapter each time a new page is out (This is what certain non PG-13 ;) extensions do). This one is not too difficult to implement, but the issue with this is that it would result in a 1129+ page chapter. This would cause huge load times for certain people. I read on a Kindle Fire HD 10 tablet and a chapter with 1129 pages would take around 11 seconds just to open the chapter, even longer if the chapter was not downloaded beforehand. For people with lower end devices, it might just straight up crash for them since their device may not be able to handle so many pages.

Now a bright idea would be to use the archives page to generate chapters and then individual pages until a chapter is complete, but once again, due to how Tachiyomi does things, this would be difficult if not virtually impossible (for any sane person).

All in all, while this is not impossible, it is very difficult to make something with a good user experience due to the way the Twokinds site is set up and how the Tachiyomi app handles things. The assumptions that they have for the site layout gives us very limited options for sites that don't follow their assumptions.

If anyone has any suggestions that address these and any other potential issues, go ahead and comment and if it is good enough hopefully someone will take and run with it.

**Comment by j2ghz** [comment]
In my abandoned PR I just went with option 2. If you use webtoon reader mode, you don't have to swipe twice, so there's no issue with too many chapters. In my opinion the other approaches are worse.

**Comment by AMDHome** [comment]
Actually. I just saw that you were the one who closed your own PR. It wasn't necessarly rejected. Is there a reason why you don't just make your own unofficial release? That way its still out there even though it never gets merged into the official branch.

**Comment by j2ghz** [comment]
Yeah, I abandoned it because I didn't have time/motivation to finish it.
> the chapter list still needs a reverse and thumbnails are missing

I think it just needs this ^ and can be merged.

**Comment by as280093** [comment]
new icon for **Keenspot** Extension
[ic_launcher.zip](https://github.com/inorichi/tachiyomi-extensions/files/5695346/ic_launcher.zip)

**Comment by AriaMoradi** [comment]
@as280093 
I found this icon that you made previously: https://github.com/tachiyomiorg/tachiyomi-extensions/pull/1150#issuecomment-500235349
If the older ones are better, notify me to change them.
