### ISSUE TITLE
[Bug] Japscan (fr) : can't acces all the list of manga

### ISSUE THREAD

**Issue by Diego10pedro** [tachiyomiorg/tachiyomi-extensions#5263]
## Device information
- Tachiyomi version: v0. 10.7
- Android version: 10

## Source information
- Name: Japscan (fr) 
- Extension version: 1.2.24

## Steps to reproduce
1. Go to explorer 
2. Search anything in japscan

### Expected behavior
Never find a manga (and they are in japscan) 

### Actual behavior
Explore the  source there is only few manga, not all the list. When you search it doesn't return anything all the time. 

## Other details
But if you go to 'recent' (last) à bigger list appear

**Comment by Zealest** [comment]
^ he's right

**Comment by sikiang** [comment]
I add one point, when you read chapter many pages are white (maybe all ads does not help)

You can also read Japscan by using EliMangas extension (JapScan (via EliMangas))

**Comment by Zealest** [comment]
> I add one point, when you read chapter many pages are white (maybe all ads does not help)
> 
> You can also read Japscan by using EliMangas extension (JapScan (via EliMangas))

Japscan via EliMangas doesn't work because the extension hasn't been updated for a long time. The change of Japscan's domain is therefore not taken into account (IIRC .co to .se).
It would also be weird to update the extension knowing that Japscan already exists as a full-fledged extension.
Atleast on my phone it doesn't work, maybe on your device it is but it would be pretty strange.
BUT, the thing that I think would be cool, would be to add JapanRead as an extension because it's like Japscan, but them, credits the translation teams.

**Comment by scb261** [comment]
Was fixed by #5630
