### ISSUE TITLE
[Bug] <Nhentai eng>: <In nhentai eng sort by recent features not working it's only shows same sort by all time popular>

### ISSUE THREAD

**Issue by Hybridcre** [tachiyomiorg/tachiyomi-extensions#5370]
## Device information
-
App version: 1.4.1 (standard, fca7dad7b, 12)
Preview build: 324
Android version: 10 (SDK 29) 
- Android version: ?

## Source information
- Name: Nhentai
- Extension version: eng

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
It should have shown recent files.

### Actual behavior
Its showing normal popular files

**Comment by Bm12347** [comment]
I am not a tachiyomi dev
But you should install the latest version

**Comment by scb261** [comment]
Weird bug, could only reproduce it on my phone but not in emulator. Happens only to sort by recent but not to other sort types. And it seems to happen randomly but I found steps that almost always causes the bug on my phone:
1. Open nhentai
2. Search `test`
3. After loading popular manga for the search, open filter and change sorting to `Recent`
4. Tap `Filter` button to apply it
5. Still see manga sorted by popular

Workaround: apply popular by week or day first, then apply recent.

Here is what I could narrow down, maybe it will help. This line returns `popular` instead of `date`
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/2364576a72c8ed14beccbfd72005ba0984696d42/src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt#L176

In this block `state` is `0` (popular) instead of `3` (date)
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/2364576a72c8ed14beccbfd72005ba0984696d42/src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt#L316-L319

**Comment by Arraiment** [comment]
Does this still happen? I can't reproduce it anywhere.

**Comment by justtry123TL** [comment]
I have the same issue, but it's weird that no body is bring it up. The extension had worked for me until I had updated it to the newest version of the extension, I had tried to delete the extension and reinstall it, but the issue still persists.

**Comment by paulo27ms** [comment]
Can't reproduce this either.
Do you have your own steps to reproduce this?

**Comment by Arraiment** [comment]
@justtry123TL it would be helpful if you could provide what you did step-by-step for the issue to occur. Also on which source specifically, eng jap cn or unfiltered.
