### ISSUE TITLE
Sawateam

### ISSUE THREAD

**Issue by CrepeTF** [tachiyomiorg/tachiyomi-extensions#5520]
## Source website
- Name: Sawateam
- Link: sawateam.info
- Language(s): English

## Other details
Scanlator, Madara theme

**Comment by DeveloperJose** [comment]
Adding just a regular Madara source without overriding any methods for SawaTeam is not enough to build this extension, it will require a bit more work. You can use the WebView to login to Discord and access the manga without problems inside the WebView so logging is not the problem. However, you cannot use "$baseUrl/wp-admin/admin-ajax.php" as you typically would to get the manga.

Here is what a regular Madara site (GourmetScans) would return with the default popularMangaRequest()
![GourmetPOST](https://user-images.githubusercontent.com/906955/106205467-ca6dd780-617b-11eb-8fa9-a65de618ed29.JPG)

Here is what SawaTeam's site returns (nothing)
![SawaPOST](https://user-images.githubusercontent.com/906955/106205468-cb066e00-617b-11eb-84ca-c9fec10a2c21.JPG)

SawaTeam is also hiding their images so they don't get ripped from the site by aggregators by showing them as HTML canvas elements instead of picture files, and as I am inexperienced in extension development I'm not sure how difficult it would be to work with those to extract the images within them.
