### ISSUE TITLE
[Bug] <动漫之家，漫画人>: <无法在webview中打开原网页>

### ISSUE THREAD

**Issue by ZerOri** [tachiyomiorg/tachiyomi-extensions#5524]
## Device information
- Tachiyomi version: 0.10.17
- Android version: 10

## Source information
- Name: 动漫之家，漫画人
- Extension version: 1.2.14，1.2.7

### Expected behavior
无法在网页中打开漫画源网页（显示一堆脚本代码而非跳转漫画页面），同样也无法分享漫画正确网址，见图

### Actual behavior
请求修复bug，让分享漫画网址功能恢复正常，另外，动漫之家被错误标记了R18标志，请求移除。

![QQ图片20210123211152](https://user-images.githubusercontent.com/46775615/105579151-b151d900-5dbf-11eb-8a8c-5844a59da8eb.jpg)

**Comment by Oldwangtouchtouchdoge** [comment]
动漫之家的webview和分享我试着修了, 然后r18内容仔细想想也夹的差不多了，我之前加nsfw标志是有点草率😂

**Comment by ZerOri** [comment]
> 动漫之家的webview和分享我试着修了, 然后r18内容仔细想想也夹的差不多了，我之前加nsfw标志是有点草率😂

嗯，在大陆运营的漫画网站，R15都不可能有，更别说R18了，就算漫画中有和谐内容远比不上真正R18的成年漫画。

**Comment by ringosham** [comment]
You should have rewritten this issue in English. This is probably why this issue went unnoticed.
About the bug:
There needs to be a change in the underlying framework. The WebView URL (The one that opens up the browser) and the API URL (That is used to look up manga) is completely different.
For example (One Punch Man):
WebView: https://manhuaren.com/manhua-yiquanchaoren/
API: http://mangaapi.manhuaren.com/v1/manga/getDetail?mangaId=10684

The WebView API can only be obtained during fetching manga details, but by that point the manga URL is fixed by the Tachiyomi framework. If we try to get the WebView API earlier (During listing latest/popular/search manga), we would be spamming the API for every single entry. That's a no go too.

**Comment by ZerOri** [comment]
> You should have rewritten this issue in English. This is probably why this issue went unnoticed. About the bug (Manhuaren specifically): There needs to be a change in the underlying framework. The WebView URL (The one that opens up the browser) and the API URL (That is used to look up manga) is completely different. For example (One Punch Man): WebView: https://manhuaren.com/manhua-yiquanchaoren/ API: http://mangaapi.manhuaren.com/v1/manga/getDetail?mangaId=10684
> 
> The WebView API can only be obtained during fetching manga details, but by that point the manga URL is fixed by the Tachiyomi framework. If we try to get the WebView URL earlier (During listing latest/popular/search manga), we would be spamming the API for every single entry. That's a no go too.
> 
> Maybe we need to submit an issue to the Tachiyomi app directly?

Thanks for reminding, but this issue was raised a long time ago and has already been fixed. 😘
