### ISSUE TITLE
Mangaplus takes more time to load compare to its webview

### ISSUE THREAD

**Issue by thapasonu** [tachiyomiorg/tachiyomi-extensions#5584]
Mangaplus takes more time to load compare to its webview

**Comment by arkon** [comment]
How much more?

**Comment by thapasonu** [comment]
> How much more?


https://user-images.githubusercontent.com/59509420/106359972-1799a700-633e-11eb-9f63-fa7cfcfa6c34.mp4

Look the clip it take this much time to load 1 part and then next takes same amount of time compare to webview

**Comment by alessandrojean** [comment]
What's your Android version?

**Comment by thapasonu** [comment]
> What's your Android version?

5.1

**Comment by alessandrojean** [comment]
I haven't faced this issue with my device neither in the emulator, the images load fast as expected, but I assume this is relative to the processing of the device, since the extension has to loop through all bytes of the image to decrypt the content. At WebView, the same behavior is happening (the decryption), but probably the WebView handles the Javascript better and do some optimizations.

I will see if I can do something to optimize the [decryption loop](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/ea862d524ac6bc33dd70dc5811c836d3e26f3643/src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus/MangaPlus.kt#L383-L400), but I can't promise anything.

For now, you can work around with this by downloading the chapter before reading.
