### ISSUE TITLE
[Bug] Mangadex : changed API url (based on log and desktop browser, or probably the old API is officially dead?)

### ISSUE THREAD

**Issue by krakerz** [tachiyomiorg/tachiyomi-extensions#5666]
## Device information
- Tachiyomi version: TachiyomiSY 1.4.1
- Android version: 10

## Source information
- Name: Mangadex
- Extension version: 1.2.103

## Steps to reproduce
1. Open the app
2. Try to open this one manga https://mangadex.org/chapter/1198802 via app (Isekai Yururi Kikou: Kosodateshinagara Boukensha Shimasu)
3. Open the latest chapter (ch28)

### Expected behavior
Chapter Loaded fine

### Actual behavior
got 404 error not found instead

## Other details

first, i'm sorry if this is wrong section since i'm using fork one (i'm quite confused where i'm posting it but since it's mangadex related, i'll post it in here)
earlier i turned the log in SY to network inspection and i've noticed the change of the API for it, probably due this one too
https://mangadex.org/thread/409315
the API from app is :
https://api.mangadex.org/v2/chapter/1198802?server=0&saver=0
while the new one (got it from Desktop Browser and open the actual chapter)
https://mangadex.org/api/v2/chapter/1198802?saver=0&include=manga

i've tested with vanilla tachiyomi too with same extension
## Device information
- Tachiyomi version: 0.10.8
- Android version: 10

strangely enough, in vanilla there is no Ch.28 listed while in SY it's listed, here i've attached them (black is SY, white is vanilla)
<details>
 <summary>Attached file</summary>
 
 https://user-images.githubusercontent.com/8030983/107139469-f2b0bf80-694d-11eb-9acd-01a44b017fd1.jpg
 
 https://user-images.githubusercontent.com/8030983/107139474-f8a6a080-694d-11eb-8fba-d02595634830.jpg
</details>

also probably related to #5627
*sorry if i'm dumb with github things

**Comment by Tenshou170** [comment]
Same here. As for SY fork, it can retrieve the latest chapter of any manga, but can't open it by giving error 404 for API change.

**Comment by scb261** [comment]
https://api.mangadex.org/v2 is the new URL, it points to separate API server that has caching issues atm (that's why you don't see new chapters and getting 404s). This one is used in the extension right now.
https://mangadex.org/api/v2 is the old URL, it points to the web server without caching issues, but this URL will be disabled by MD in future.

Switching back to the old URL is bad idea because:
- It will be disabled in future.
- MD web server already has issues because of too many users. Redirecting tachi users (that is huge part of MD userbase) to the web server will only cause more 502 errors that won't allow to read even old chapters.

MD devs are working on both web server issues and API server caching issue, wait patiently until they fix it.

**Comment by arkon** [comment]
Also see #5780 for more info.
