### ISSUE TITLE
[Bug] Mangazuki.online, KlikManga, Kombatch: can't be installed

### ISSUE THREAD

**Issue by samanta-widjaja** [tachiyomiorg/tachiyomi-extensions#5721]
## Device information
- Tachiyomi version: 0.10.8
- Android version: 7.1.1

## Source information
- Name: Mangazuki.online, KlikManga, Kombatch
- Extension version: 1.2.1

## Steps to reproduce
1. Install extension dan got installed status
2. After gone to download queue, the status back to install

### Expected behavior
The extension should be installed

**Comment by scb261** [comment]
Try to download manually from the site https://tachiyomi.org/extensions/

**Comment by samanta-widjaja** [comment]
Already tried that, but still not working.

**Comment by scb261** [comment]
Try to install them with SAI https://play.google.com/store/apps/details?id=com.aefyr.sai&hl=en_US

**Comment by samanta-widjaja** [comment]
Doesn't work. Sai install it fine, but it status in tachiyomi still install

**Comment by scb261** [comment]
Does tachi have access to other apps?

**Comment by samanta-widjaja** [comment]
I don't know about that, but thanks for trying to help

**Comment by ardhanasan** [comment]
same problem

**Comment by arkon** [comment]
Fixed by https://github.com/tachiyomiorg/tachiyomi-extensions/commit/a3a78c0323abece1009b5e8bf9f5482d9e6e4da3 and https://github.com/tachiyomiorg/tachiyomi-extensions/commit/db38a0b4e63f1e26feb2b81e872430b0ed4388c5 .

You'll need to reinstall the extensions. The Mangazuki.online fix should be available in ~20 minutes.
