### ISSUE TITLE
[Bug] Manatoki: Update rate limit needed

### ISSUE THREAD

**Issue by Yun-ssi** [tachiyomiorg/tachiyomi-extensions#5934]
## Device information
- Tachiyomi version: r3121 (89837e4c)
- Android version: 7.0

## Source information
- Name: Newtoki/Manatoki
- Extension version: 1.2.20

## Steps to reproduce
1. Update from main menu 
2. HTTP 403 error after requesting for multiple, favorite manga in database. 

### Expected behavior
Expected Manatoki manga show new releases and would slow down at about 60% of my update (other extensions update prior to this for me). 

### Actual behavior
Failed to update rest of the selections that are available and update continues on with available extensions.  
Received temporary IP ban.

## Other details
I think the new update removed the rate limit that was there prior to this update. 
I've updated fine on my other device with 1.2.19 version. 
It worked fine as well when I downgraded to 1.2.19.

**Comment by DitFranXX** [comment]
Well, I reduced ratelimit to 1 request per 1 seconds in 1.2.20. (previously it was 2 req per 5 seconds). When I tested, I didn't get a ip ban. 
However, It may has a difference by IP CIDR range. Since I only tested on mobile network. (As the cellular IPs are shared by many users that means much more access with same IP).
Considering revert... or make it as opt-in on settings.

**Comment by Yun-ssi** [comment]
I think the 2 per 5 seconds is okay as is.
I access their website with wifi and vpn so it seems to trigger a flag
easily.
Thank you for looking into it.
