### ISSUE TITLE
[Bug] <Super Mangás>: <Error in manga covers everything is without profile and does not even load notifications of manga release.>

### ISSUE THREAD

**Issue by desenvolvedor2021** [tachiyomiorg/tachiyomi-extensions#5949]
---
## Device information
- Tachiyomi version: v0.10.9

- Android version:8.1.0 (SDK 27)
 Device model: Moto G (5S)

## Source information
- Name: Super Mangás
- Extension version: 1.2.5

## Steps to reproduce
1. Loading of covers
2. Release of the manga and show the dates in the chapters that do not appear are only blank

### Expected behavior
Describe what should have happened

The source of the Super Manga should work with the loading of covers and also the updates of the new chapters, as well as showing the release dates and missing new manga already released that are not in the extension of the super manga.

### Actual behavior
Describe what happens instead

The extension where I downloaded the Super Mangás app, like it happens that the covers don't load and on the screen a warning appears saying that there was an error loading the covers and I also don't receive notifications of manga releases to read the extension of the super manga doesn't work.

## Other details
Other details I discovered was that the super manga extension can be added to the library normally
and there’s no way to update the covers or receive updates on the manga and more,I can read them without any error, but there is no way to receive updates when the manga arrives and there is also no way to see the release dates and the chapter lists are blank.
  
(I Hope You Can Work This Out Thanks.)

**Comment by alessandrojean** [comment]
> missing new manga already released that are not in the extension

Can you provide some examples?

> there is no way to receive updates when the manga arrives

This maybe can be related to your phone killing the Tachiyomi process in the background.

> chapter lists are blank

In all mangas or only some? Can you provide examples for this too?

> showing the release dates

The site itself [does not have](https://www.supermangas.site/manhwa/solo-leveling) this information in the manga page, so there's no way to the extension to guess it.

**Comment by desenvolvedor2021** [comment]
Can you provide some examples?

R: like I don't get the manga chapters as well as the release dates. 

Look at this print of the lists in one of the manga other than the cover.![Screenshot_20210221-124947.png](https://user-images.githubusercontent.com/79285956/108632118-a4b6b400-7443-11eb-86ba-90b67df800d2.png)


This maybe can be related to your phone killing the Tachiyomi process in the background.

R: well I already checked it and I didn't see anything wrong in the background like if it had interfered the other sources would not be working and I went to see the analysis of errors and not any problem.

In all mangas or only some? Can you provide examples for this too?

R: If I'm talking about all the manga with the same problem, it was only in the source of Super Mangás so the other sources are normal. I'll send the print here.

![Screenshot_20210221-125821.png](https://user-images.githubusercontent.com/79285956/108632294-8309fc80-7444-11eb-92ed-422f14cbc2dc.png)

good to notice that when I enter to read the list of chapters it does not load the dates as well as the profiles of the manga, like I went to check the source of the super manga like the list was blank,almost didn’t show the names and the covers don’t load if you see them on the prints. I have tried several ways to resolve this issue further came after the update of tachiyomi.

**Comment by alessandrojean** [comment]
> as well as the release dates

> it does not load the dates

Like I said before, the site itself **does not provide this information**, as you can see below, so there's no way to the extension to guess this. It will be empty and there's nothing that can be done to change this for now.

![image](https://user-images.githubusercontent.com/14254807/108632488-ff550d80-744d-11eb-8796-4b12dc43db58.png)

> the covers don’t load

About the images, for me, they are loading fine in the popular list, but not on the latest. What happens is that the site is giving image URLs that does not exist or that have errors, you can try one [here](https://img.supermangas.site/?src=img/animes/15028-large.jpg&w512). This is a site problem, and you have to wait them to fix it, there's nothing that can be done on the extension for now.

@Shironep, are you still an uploader in the site? Can you contact the developer and tell that the cover images are not loading if you access them by their direct URL? They sometimes do load in a browser inside the site, but if you access them directly by [their URL](https://img.supermangas.site/?src=img/animes/62991-large.jpg&w512) (even in a browser), it's just a blank HTML page instead of the correct JPG file.

**Comment by desenvolvedor2021** [comment]
Hmm I’m going to see here with the owner of the site to find out if it’s a problem there, good if it’s not there. I do not know if it is the problem with the server link that interrupted.

**Comment by alessandrojean** [comment]
I think it's not necessary, I managed to *temporary* fix the image problem inside the extension.

Wait for the update and open a new issue if it still happens.

You may need to clear the database, cache and cookies after the extension update though.

**Comment by desenvolvedor2021** [comment]
It worked, I just updated it and the images already loaded I had to delete the manga that were added to the library, well I'm just waiting to load it right because the Net here pulled too much then I thank you for correcting the errors.
