### ISSUE TITLE
[Bug] <ManhuaES> when I try to download Return of Immortal emperor (last 5 chapters or last chapter of any manhua it showing no page but on website there are page) 

### ISSUE THREAD

**Issue by SingiuStefan** [tachiyomiorg/tachiyomi-extensions#6084]
## Device information
- Tachiyomi version: 0.10.9
- Android version: 10(EMUI 10. 1)

## Source information
- Name: ManhuaES 
- Extension version: 1.2.2

## Steps to reproduce
1. Head to Return of Immortal emperor or any manhua last chapter 
2. Download 

### Expected behavior
Should download chapters 

### Actual behavior
No page found but on website there are

**Comment by scb261** [comment]
Works for me, did you try [troubleshoot](https://tachiyomi.org/help/guides/troubleshooting-problems/#diagnosis)?

**Comment by SingiuStefan** [comment]
I did every thing but if this is still going on i will try to move to another extension

**Comment by scb261** [comment]
Can you try removing chapter folders with a file manager?

**Comment by Riztard** [comment]
what about read without download

**Comment by SingiuStefan** [comment]
So did that and at chapter folder shows _172 chapter_tpm (AT the chapters that i tried to download at all other chapters shows just chapter and number)

**Comment by SingiuStefan** [comment]
If i try to read without download still shows no page found: webview dosen't open on Return of Immortal Emperor

**Comment by scb261** [comment]
Never mind, I just tried the latest chapter (178) and it actually doesn't work, but it's the same in WebView - the chapter isn't released yet. The extension should be changed to filter them out.

Chapters from your screenshot on discord probably don't work because you tried to download/read them when they weren't released. Clear chapter cache, remove folders for those chapters and try again.
