### ISSUE TITLE
[Bug] <Lily Manga>: <Webview loads; Not able to view chapter>

### ISSUE THREAD

**Issue by Kelbi-horn** [tachiyomiorg/tachiyomi-extensions#6292]
---

## Device information
- Tachiyomi version: Preview r347 (3a148c73a)
- Android version: 11

## Source information
- Name: Lily Manga
- Extension version: 1.2.1

## Steps to reproduce
1. Selected "A Village Protected by a Dragon" series in the 'Library' tab
2. Clicked on Chapter 2 
3. Also tried clicking Resume

### Expected behavior
Should be able to view the chapter

### Actual behavior
Sometimes got "HTTP error 500"
Sometimes got "No Pages Found"

## Other details
In Browse Tab - getting HTTP error 500 for Lily Manga
In Library Tab - Viewing the manga series - Webview loads fine and able to load chapter through webview

**Comment by scb261** [comment]
HTTP error 500 probably was some temporary issue on the site, since it works now.

~~As for manga page and chapters on it - the site uses `Sucuri CloudProxy` protection, that acts like `Cloudflare` protection, but it's harder to pass. Basically, the site sends a page with `Javascript is required. Please enable javascript before you are allowed to see this page.` text and obfuscated JS (base64 and `eval()`) to set cookies with the right token, and after this the code reloads the page. Since the app doesn't load JS, it gets `Javascript is required. Please enable javascript before you are allowed to see this page.` as a manga page. This happens only to manga page, since browse and latest do work in the app.~~

As for manga page and chapters - you need to open a **manga page** in WebView to bypass site protection, since the site doesn't use the protection for browse/latest. After this chapters will work fine.

If something still doesn't work - please comment and I'll reopen the issue.
