### ISSUE TITLE
[Source Request] Immortalsunscan

### ISSUE THREAD

**Issue by aSimpleGuy** [tachiyomiorg/tachiyomi-extensions#6303]
### Source website

-  Name: Immortalsunscans

- Link: https://immortalsunscans.com

-   Language(s): en

**Comment by jopejoe1** [comment]
Uses MangaReader theme

**Comment by alekc** [comment]
Using the generator manga search, pages, etc work all fine. However, the image download goes in timeout due to a slow as xx cdn 
i.e.
```
➜ curl https://immortalsunscans.com/wp-content/uploads/2021/07/19-1.jpg -o test.
jpg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9.8M  100  9.8M    0     0  86671      0  0:01:59  0:01:59 --:--:--  346k
```

as consequence, it just times out in tachiyomi. Not sure if it's worth doing any extra work as consequence (or how it can be improved on the code site to disable timeouts)
