### ISSUE TITLE
[Bug] Mangá Livre: Mangas don't update

### ISSUE THREAD

**Issue by plsouza12** [tachiyomiorg/tachiyomi-extensions#6475]
## Device information
- Tachiyomi version: **0.10.9**
- Android version: **galaxy note 9**

## Source information
- Name: **Mangá Livre** 
- Extension version: **1.2.2**

## Steps to reproduce
1. First Step= **open latest, in the source**

### Expected behavior
**Show the latest mangas updated/ update the mangas**

### Actual behavior
**Don't show the new updates and don't update the mangas**

## Other details
**I tried the troublesooting steps, but didn't work
Is stuck in this manga" My friend's gotta c*m to use magic, solmis channel.**

**Comment by alessandrojean** [comment]
If you open the site and click on the ["Todos" button](https://user-images.githubusercontent.com/14254807/114036263-4eb49900-9856-11eb-98b7-d2397485c18c.png), you'll see that the extension are showing exactly the same recent list from the site, as you can see on the images below.

| Extension | Site |
| ------------- | ----- |
| ![Screenshot_1617888407](https://user-images.githubusercontent.com/14254807/114035665-b1f1fb80-9855-11eb-9de8-d3c60820cf2d.png) | ![Screenshot_1617888427](https://user-images.githubusercontent.com/14254807/114035677-b4ecec00-9855-11eb-870a-f64e8e5a0c56.png) |

The extension uses the list with all the releases, and not the list with only manga, so it's because of this that you think that it's not showing the updates, but it's showing exactly the same from the site. If it's the case that the site it's not showing them correctly, then it's a site issue and nothing can be done on the extension side to fix it.

Beyond that, the site is most probably having cache issues on their end, because some days ago the new chapters are showing in the initial page, but not on the manga page. Since this is also a server/site issue, there's nothing that can be done on the extension, just wait to the site fix itself.

About the manga you mentioned, I can open just fine and can't see any issue with it.

**Comment by plsouza12** [comment]
Thank you so much, for the help,
If you're talking about solmis / my friend's gotta. I was just referring to which ones were appearing in the "latest" in case anyone who helped me see which ones were stuck, there's nothing wrong with them for me too.

**Comment by alessandrojean** [comment]
I checked now, for some reason on my PC it's the same from the image, but on mobile it's different. Most probably is still related to the cache issue on the site, but I will see if I can do something.

**Comment by alessandrojean** [comment]
I took a deep look, and the recent list in Chrome is outdated (the chapters marked as released today were released yesterday, and you can check this by opening the manga page and checking the dates), so it's indeed a cache issue on their end on mobile. However, if you check the list on the images I have shown, they are correct (the chapters marked as released today were released today), so the extension is showing the most updated mangas, and they are the same in WebView and on Chrome on a PC.

I will submit a fix to a JSON error, but it's not related to this problem with the recent list, since nothing can be done.

**Comment by plsouza12** [comment]
Ok
