### ISSUE TITLE
[Bug] Mangá Host: Mangás não atualizam e dá Error 403 individualmente

### ISSUE THREAD

**Issue by kr1sthyan** [tachiyomiorg/tachiyomi-extensions#6537]
## Device information
- Tachiyomi version: 0.10.10
- Android version: 10 QKQ1..200114.002

## Source information
- Name: Mangá Host
- Extension version: 1.2.21

## Steps to reproduce
1. Mangá salvo na Biblioteca pela extensão Mangá Host
2. Tendo atualizar os capítulos do mangá e o mesmo retorna o Error 403

### Expected behavior
O mangá deveria atualizar normalmente, mostrando ou não novos capítulos

### Actual behavior
Porém está retornando apenas o Error 403 e não atualiza mesmo quando tento atualizar todas as bibliotecas

## Other details
Erro vem acontecendo há 2 dias e não resolveu mesmo após limpar o cache do app e mesmo testando redes diferentes

**Comment by alessandrojean** [comment]
Tente abrir algum mangá no WebView e resolver o captcha que aparece do Cloudflare, e depois disso tentar carregar novamente. É necessário fazer isso de tempos em tempos.

Caso mesmo após isso ainda não consiga acessar, não tem muito o que ser feito pela parte da extensão, já que o site está sempre tentando bloquear o Tachiyomi, somente migrar para uma fonte melhor.

**Comment by jasperalbarn** [comment]
Dear,

I admire Tachiyomi's work and quality. I avoided contacting you, but as the technician responsible for the site (mangahosted.com / mangahostz.com) I have to say and explain that **Tachi simply consumes 50% of the bandwidth and 40% of the site's CPU**. Every time the APP starts to work, everything is slow. It is very complicated to stay in this Lock x Unlock war. Some users seem to want to download the site at once... Who are users of the site who use Tachi about, because eventually the Fixed IPs of these visitors are permanently blocked.

**I formally request the removal as a reading source PT from mangahost**. If it is not possible, we will continue this until someone gets tired... PS. We are the most disadvantaged side...

**Comment by jasperalbarn** [comment]
@kr1sthyan @alessandrojean Normalmente estamos dando Block permanente CloudFlare e IPTables nas subredes dos IPs. Essa é uma briga sem sentindo que o lado mais prejudicado serão os usuários de ambos: Tachi e MangaHost.

A gente bloqueia o Tachi, porque simplesmente o Load do site vai pro espaço na que começam a usar. A maioria dos usuários não tem limite e parecem querer baixar o site todo de uma vez. O site fica muito lento. Pensem pelo nosso lado de ter algo consumindo recursos sem nenhum retorno...

**Comment by alessandrojean** [comment]
@jasperalbarn Infelizmente há este caso de usuários que abusam dos downloads e prejudicam os demais que usam casualmente. Para amenizar isso, o rate limit da extensão foi atualizado para permitir com que ela só possa fazer uma única requisição a cada três segundos por agora (PR #6540). O rate limit só se aplica as páginas do site no momento, mas vou submeter um PR para estender para tudo, incluindo as imagens. Atualize-nos, se possível, se isto deu/dará uma aliviada no servidor ou não.

Caso continue muito massivo, eu submito um PR novo para remover a extensão, porque pessoalmente não gosto de ficar neste [jogo de gato e rato](https://en.m.wikipedia.org/wiki/Cat_and_mouse) infinito, é cansativo e tedioso para ambas as partes, como você mesmo disse.

**Comment by kr1sthyan** [comment]
Uma pena que esse seja o caso, mas entendi a situação, já nos acostumamos a pagar pelo erro de outrem.
