### ISSUE TITLE
[Bug] Mangakawaii: Error http or https

### ISSUE THREAD

**Issue by moi15moi** [tachiyomiorg/tachiyomi-extensions#6547]
## Device information
- Tachiyomi version: Stable 0.10.10
- Android version: 10

## Source information
- Name: MangaKawaii
- Extension version: 1.2.29

## Steps to reproduce
1. Try to download the last chapter: https://www.mangakawaii.com/manga/solo-leveling
2. Got the error

### Expected behavior
It should download the chapter.

### Actual behavior
It do not download the chapter.

## Other details
I get the error: Expected URL sheme 'http' or 'https' but was 'data' (_I can't see the rest of the error message_)

**Comment by papjul** [comment]
It's the cat and mouse game with this website. Honestly, I would migrate my library to another extension. If you really want to stick with MangaKawaii, you can just skip the first pages of the chapter. I will try fixing the extension but it's just a matter of time until another issue arises since I'm almost sure extension updates are monitored.

**Comment by moi15moi** [comment]
There is not really other good french website in tachiyomi ^^'
If you know any alternative, I take it.

**Comment by papjul** [comment]
Scan-Manga, Japanread, Japscan, some Madara extensions or MMRS, etc
