### ISSUE TITLE
[Bug] <Union Mangás>: <fails to get around Cloudflare>

### ISSUE THREAD

**Issue by MarcosSouza2004** [tachiyomiorg/tachiyomi-extensions#6564]
## Device information
- Tachiyomi version: 0.10.10
- Android version: A11

## Source information
- Name: Union Mangás
- Extension version: 1.2.19

## Steps to reproduce
1. First Step
2. Second Step

### Expected behavior
Connect and read mangas

### Actual behavior
Cloudflare bug

## Other details
![image](https://user-images.githubusercontent.com/76596575/114887483-df532200-9dde-11eb-8789-930133aae965.png)

**Comment by alessandrojean** [comment]
I took a look just before you created this issue, and it's a Cloudflare loop issue. This happens with some other extensions and until now there's no known fix that can be done on the extension side.

Only thing you can do is keep trying to bypass the Cloudflare page on WebView and see if the source fix itself. In some cases after a while this problem is gone, but in the worst case it's better to migrate to another source.

**Comment by MarcosSouza2004** [comment]
> I took a look just before you created this issue, and it's a Cloudflare loop issue. This happens with some other extensions and until now there's no known fix that can be done on the extension side.
> 
> Only thing you can do is keep trying to bypass the Cloudflare page on WebView and see if the source fix itself. In some cases after a while this problem is gone, but in the worst case it's better to migrate to another source.

i take the point, thanks.....but why the sites do this? I mean try to block tachiyomi (like MangáHost and SuperMangás)

**Comment by alessandrojean** [comment]
My guess is that it's mostly because of the ad revenue. Tachiyomi is a fancy browser, but it doesn't process the ads on the page and neither the JavaScript required to show them. So, the sites gets a lot of requests from the app, but none of them returns a revenue for them. But it can be other reasons too.

**Comment by MarcosSouza2004** [comment]
> My guess is that it's mostly because of the ad revenue. Tachiyomi is a fancy browser, but it doesn't process the ads on the page and neither the JavaScript required to show them. So, the sites gets a lot of requests from the app, but none of them returns a revenue for them. But it can be other reasons too.

have a way to alow the ads for the sites? like a button called "allow ads in this extension"

**Comment by alessandrojean** [comment]
No, and I think it's out of the scope of the app.

**Comment by MarcosSouza2004** [comment]
> No, and I think it's out of the scope of the app.

ok, thanks a lot, you are very helpful ;)
