### ISSUE TITLE
[Bug] Tao Sect: When I log in to WebView, it goes to the site, but loads again and goes to an empty site

### ISSUE THREAD

**Issue by Kaylenna** [tachiyomiorg/tachiyomi-extensions#6842]
## Device information
- Tachiyomi version: 0.10.12
- Android version: 8.1.0

## Source information
- Name: Tao Sect
- Extension version: 1.2.3

## Steps to reproduce
1. Go to explore
2. Menu sources
3. Tap on the Tao Sect source name
4. Go to WebView

### Expected behavior
See the website in WebView

### Actual behavior
![Screenshot_20210505-203433_Tachiyomi](https://user-images.githubusercontent.com/82852543/117222225-5c235b80-ade1-11eb-9460-bdc20207dadb.jpg)

![Screenshot_20210505-203440_Tachiyomi](https://user-images.githubusercontent.com/82852543/117222316-8bd26380-ade1-11eb-999e-cc7bd4f488f8.jpg)

**Comment by alessandrojean** [comment]
Is there any specific reason that you need to login via WebView? As I know, you can read the titles just fine without any login required.

Usually the extension has no control of the behavior of the site in the WebView, so if it's returning this url to you after the login, there isn't much that can be done on the extension to fix it, since it looks like a site error.

**Comment by Kaylenna** [comment]
Sorry, it’s just that when I got into the manga he didn’t carry it, but I went to see it now and they carry it, I should have seen it before, sorry for the inconvenience

**Comment by alessandrojean** [comment]
No problem. This issue can be closed since the extension is working as expected. If there's a new problem, feel free to open a new issue.

**Comment by Kaylenna** [comment]
Thanks for attention ☺
