### ISSUE TITLE
[Bug] Webtoons.com: Titles in Library do not display as such in Browse

### ISSUE THREAD

**Issue by jadoff630** [tachiyomiorg/tachiyomi-extensions#7024]
## Device information
- Tachiyomi version: SY r371
- Android version: 10

## Source information
- Name: webtoons.com
- Extension version: 1.2.28

## Steps to reproduce
Titles in the library from the extension at times do not appear as greyed out or marked in the library when browsing the extension. Some of the titles appear correctly, but others do not. 

### Expected behavior
When a title is added to the library, they usually they appear as greyed out when browsing the extension 

### Actual behavior
Some of the titles no longer appear greyed out and when you select the titles they do not say that they are in the library.

**Comment by scb261** [comment]
Apparently the extension returns the same manga with different URLs:
```
Browse/Latest
https://www.webtoons.com/en/romance/subzero/list?title_no=1468

Search
https://www.webtoons.com/episodeList?titleNo=1468
redirects to
https://www.webtoons.com/en/romance/subzero/list?title_no=1468
```
Converting browse link to search link would mean forcing unnecessary redirect. Converting search link to browse link would require extra network call for each found manga since we don't have enough info for it. I think it's better to leave the extension as is, but it's up to maintainers.

**Comment by CarlosEsco** [comment]
closing in favor of other ticket since it has more info.  I will copy over your last comment scb
