### ISSUE TITLE
Replace Gson and org.json with kotlinx.serialization

### ISSUE THREAD

**Issue by alessandrojean** [tachiyomiorg/tachiyomi-extensions#7392]
##  Why/Project's Benefit/Existing Problem

There are in the repo actually:
- ~~[1 file](https://github.com/tachiyomiorg/tachiyomi-extensions/search?q=%22com.google.gson.Gson%22) that uses Gson;~~
- ~~[4 files](https://github.com/tachiyomiorg/tachiyomi-extensions/search?q=%22com.google.gson.JsonParser%22) that uses JsonParser from Gson;~~
- ~~[14 files](https://github.com/tachiyomiorg/tachiyomi-extensions/search?q=%22com.github.salomonbrys.kotson%22) that uses Kotson; and~~
- [7 files](https://github.com/tachiyomiorg/tachiyomi-extensions/search?q=%22org.json%22) that uses org.json

All the usages of other Json libraries for deserialization should be replaced by kotlinx.serialization.

## Other details

The `Json` singleton instance with `ignoreUnknownKeys = true` from the main app can be reused:

```kotlin
private val json: Json by injectLazy()
```

It is not needed to add the kotlinx.serialization dependency to the extensions that uses it (with Json or ProtoBuf), since it was already added to `common-dependencies.gradle`. However, extensions that make usage of the library **must** add this one line after the `kotlin-android` plugin at the extension's Gradle file:

```gradle
apply plugin: 'kotlinx-serialization'
```

## Additional documentation

- [Using Json from kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md)
- [Using ProtoBuf from kotlinx.serialization](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/formats.md#protobuf-experimental)
- [Example of Json usage in extension](https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/pt/bruttal/src/eu/kanade/tachiyomi/extension/pt/bruttal)
- [Example of ProtoBuf usage in extension](https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/all/mangaplus/src/eu/kanade/tachiyomi/extension/all/mangaplus)

**Comment by ObserverOfTime** [comment]
I don't understand why you're replacing the builtin `org.json` with an external library that isn't actually any better..

**Comment by CarlosEsco** [comment]
consistency across extensions.

**Comment by h-hyuuga** [comment]
> I don't understand why you're replacing the builtin `org.json` with an external library that isn't actually any better.

[Kotlinx.serialization](https://kotlinlang.org/docs/serialization.html) is an official library

**Comment by ObserverOfTime** [comment]
An official library that is not part of the Android API.

**Comment by CarlosEsco** [comment]
It's an official Library with first class kotlin support and allows you to actually deseralize to data classes

**Comment by ObserverOfTime** [comment]
Which would be great if we actually used serializable data classes.

**Comment by CarlosEsco** [comment]
Which we do now go away

**Comment by Soitora** [comment]
/edit-title "Replace Gson and org.json with kotlinx.serialization"

**Comment by arkon** [comment]
Gson and Kotson need to be removed so that they can be removed from the app. I'm impartial to the usages of `org.json`.

**Comment by h-hyuuga** [comment]
A couple observations made while using kotlinx.serialization

# Automatically Generated (De)Serializers

* **Pros**: Everything essentially happens transparently, type safety, etc...
* **Cons**: @Serializable Classes aren't always appropriate
   `e.g`: Comick.fun's api doesn't return objects with a consistent structure, even when they're meant to represent the same thing across different endpoints (manga, chapters, etc...). Making it difficult to make meaningful classes which represent the transferred data.

# Raw Manipulation of JsonElements
 
 ###  Walking down JsonElements with accessor methods: :(
 
 * **Pros**: No need to come up with @Serializable classes
 * **Cons**:  Verbose af
    e.g: `{"data": [1,2,3,4,5]}`
    `val numbers = elem.jsonObject["data"]!!.jsonArray.map { it.jsonPrimitive.int }`
   

 ### decodeFrom(JsonElement|String)
 
* **Pros**:  Can be much more readable than the above, since you can leverage type inference + built-in serializers
    e.g: `{"data": [1,2,3,4,5]}`
    `val numbers: List<Int> = json.decodeFromJsonElement(elem.jsonObject["data"]!!)`
 
 # Non-Trivial Applications of kotlinx.serialization
 
 ### Custom Deserializers
 
 * **Pros**: No need to come up with @Serializable classes
 * **Cons**: Depends on implementation strategy
   * Can come down to doing the same raw manipulation described above (see MangaMutiny)
 
 e.g:
 
 MangaMutiny: https://github.com/tachiyomiorg/tachiyomi-extensions/blob/d4336e2ace4a20338b4f5fb6af6827521af0a805/src/en/mangamutiny/src/eu/kanade/tachiyomi/extension/en/mangamutiny/MangaMutinySerialization.kt#L39-L53
 
 Comick.fun (uses KSerializers instead of DeserializationStrategy to allow them to be registered): 
 
 Registration:
 
 https://github.com/tachiyomiorg/tachiyomi-extensions/blob/1175b0d1c70b3fdf5d5742b10d21e0c8e69261ff/src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt#L41-L49
 
 https://github.com/tachiyomiorg/tachiyomi-extensions/blob/1175b0d1c70b3fdf5d5742b10d21e0c8e69261ff/src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunSerialization.kt#L101-L175
 
 ### Debugging

Debugging kotlinx.serialization bugs can be difficult, since they don't give a ton on context as to what caused the error.

**Comment by h-hyuuga** [comment]
Also, was wondering if there'd be any merit to making a library in this repo to house some utilities to facilitate using `kotlinx.serialization`

I'm mostly interested in making this bit of code available

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/1175b0d1c70b3fdf5d5742b10d21e0c8e69261ff/src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunSerialization.kt#L27-L68

Since it makes it easier to select deeply nested structures in json objects

https://github.com/tachiyomiorg/tachiyomi-extensions/blob/1175b0d1c70b3fdf5d5742b10d21e0c8e69261ff/src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt#L235-L240

**Comment by alessandrojean** [comment]
> Also, was wondering if there'd be any merit to making a library in this repo to house some utilities that facilitate parsing with kotlinx.serialization

We could maybe write some extension functions in a library inside the repo, like Kotson does with Gson, but for JsonElement, and include in all extensions, similar to the `RateLimitInterceptor`.

Some extensions can be made like: 

```kotlin
// Instead of:
val value = jsonObj["data"]!!.jsonObject["innerField"]!!.jsonPrimitive.content
// Use:
val value = jsonObj["data"]["innerField"].string
```

**Comment by arkon** [comment]
Closing this since replacing `org.json` isn't really necessary, although it is a nice-to-have.
