### ISSUE TITLE
[Bug] <Imperfect Comics>: <403 error on browse, webview normal>

### ISSUE THREAD

**Issue by Matakor** [tachiyomiorg/tachiyomi-extensions#7493]
## Device information
- Tachiyomi version: r3497
- Android version: 10

## Source information
- Name: Imperfect Comics
- Extension version: 1.2.5

## Steps to reproduce
1. Try to browse Imperfect comics
2. Get 403'd

### Expected behavior
Not 403'd and seen comics.

### Actual behavior
Got 403'd.

## Other details
New install of extension, no prior info. Webview open and back to retry didn't help, cookies and cache clear shouldn't be an issue since it's a new install.

**Comment by Clouddark75** [comment]
They used a complex Cloudflare version. You will need to open it on WebView first before using the extension.

**Comment by Matakor** [comment]
I have. I keep all apps updated. Cloudflare passes through fine, webview sees it fine, but I still can't see it in browse

**Comment by Clouddark75** [comment]
And I understand that, but I have tested it on two devices so far, and after passing through Cloudflare I can search or update titles from the that website. Make sure your WebView is update to the lastest version on the PlayStore.

**Comment by Matakor** [comment]
Updated as of jun 2, 2021. Nothing to update

**Comment by Clouddark75** [comment]
I didn't have to change my DNS, it's probably that your cache/cookies didn't clear at all.
- Not much it can be done. If they decide to use a more aggressive Cloudflare approach (some can't be be bypassed because Cloudflare will block your access to the page), there won't be another option than removing the source. 
- Thachi has nothing to do with websites' decisions to prevent and protect themselves from heavy traffic or fetch their site. So, my recommendation will be to migrate to another source if it's bothering you.
