### ISSUE TITLE
[Bug] Hiperdex still broken after update

### ISSUE THREAD

**Issue by HeartzSoulz** [tachiyomiorg/tachiyomi-extensions#7718]
I have updated it restarted it 

- I have updated:
  - To the latest version of the app (stable is v0.11.1)

## Device information
- Tachiyomi version: App version: 0.11.1 (standard, 0f3f1e9, 63, 2021-05-31T23:39Z)
Android version: 9 (SDK 28)

## Source information
- Name: Hiperdex
- Extension version:1.2.10

## Steps to reproduce
I have the lastest version downloaded and have restarted my app just incase 

### Expected behavior
Should work after the event update but doesn't 

### Actual behavior
Doesn't load black screen with HTTP 400 error and can't access any of the manga

## Other details
First time it's happened since using Hiperdex was told by someone on Reddit to report bug here

**Comment by joseph619** [comment]
Might need to rate limit the ext next time

**Comment by richmond2010** [comment]
The url was changed to hiperdex2.com for about a day yesterday which resulted in the broken extension, and since the fix was to change the url in madara, it got broken again when it reverted to hiperdex.com a few hours ago.

I think it might be best to future-proof the fetching system in case it goes back to hiperdex2.com in the future, instead of changing the url back to hiperdex.com.
