### ISSUE TITLE
Kuaikanmanhua: Account Login

### ISSUE THREAD

**Issue by openube** [tachiyomiorg/tachiyomi-extensions#7910]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

Please add account login or connect session with webview, in order to download purchased chapters. I recommend a session linked to the webview if possible.

FYI, Rosabis has reported this as [bug](https://github.com/tachiyomiorg/tachiyomi-extensions/issues/7556) in this issue. This feature request is fundamentally related to Rosabis' bug, but I hope to formalize it so you could consider it as a feature request.

**Comment by anenasa** [comment]
Hello, I think the reason is that this extension uses api (https://api.kkmh.com) to parse chapter and pages. I tried sending cookies to the api, but this doesn't work, so I think baseUrl should be used and parsed. I browsed the source of a chapter, and url of images is in a script. I will look into it.
