### ISSUE TITLE
Domain problem in extensions

### ISSUE THREAD

**Issue by wankio** [tachiyomiorg/tachiyomi-extensions#7998]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I will fill out all of the requested information in this form.

### Describe your suggested feature

As you know there are nettruyen extension, but they keep change domains. So i think this extension should match regex nettruyen[xxxx] instead fixed domain

Their domain recently changed : nettruyen -> nettruyentop -> nettruyenvip

### Other details

Or give end-user ability to edit extensions in-app, so they can just change domain by their own

**Comment by Clouddark75** [comment]
Is counterproductive, not all the website have the same tags or configuration despite using the same theme. And there's another problem, some sources have been asked for deletion from their site owners, so, it's something that won't happen any time soon or ever.
Those sites that keep changing stuff from their pages, do it intentionally, they simply don't want their site scrapped by App or bots, I can only recommend you to migrate to another source, because in the end if they keep like that, that source probably won't be updated and deleted from the extension repo.
