### ISSUE TITLE
MangaDNA

### ISSUE THREAD

**Issue by CVIUS** [tachiyomiorg/tachiyomi-extensions#8008]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

### Source name

MangaDNA

### Source link

https://mangadna.com

### Language

English

### Other details

- madara ?
- icon -> [mangadna.zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/6784180/mangadna.zip)

**Comment by vetleledaal** [comment]
The CSS makes it look like Madara, but it doesn't behave like it at all.
- `/wp-admin/admin-ajax.php` returns 404 instead of 200 with the content "0"
- Manga is listed at `/manga` and not `/manga/`
- Offers to order by "Latest", "A-Z", "Rating", and "Trending" instead of "Latest", "A-Z", "Rating", "Trending", "Most Views", and "New"
