### ISSUE TITLE
MangaDex: Popular broken( JSON token at offset 7069)

### ISSUE THREAD

**Issue by FourTOne5** [tachiyomiorg/tachiyomi-extensions#8011]
### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.11.1](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### Tachiyomi version

0.11.1-3556

### Android version

Android 6

### Source information

MangaDex 1.2.121

### Steps to reproduce

1. Click on Popular.

### Expected behavior

Popular Manga Should Appear

### Actual behavior

![Screenshot_20210708-182941](https://user-images.githubusercontent.com/59261191/124922626-7d8c0800-e01b-11eb-8394-07e07484b8e0.png)

### Other details

Latest Update still missing though its API Endpoint is available.

**Comment by CarlosEsco** [comment]
sounds like people are updating some broken manga.

As for latest updates, that needs a complete rework.  
https://api.mangadex.org/docs.html#operation/get-search-manga
This is the normal search endpoint, and Dex decided that when a chapter is uploaded for a manga it doesn't actually affect the update date for a manga (only manga info changes that information)  so it needs to use this endpoint
https://api.mangadex.org/docs.html#operation/get-chapter
deedupe, and mention that no other filter can be used during..

**Comment by FourTOne5** [comment]
> 
> 
> sounds like people are updating some broken manga.
> 
> As for latest updates, that needs a complete rework.
> https://api.mangadex.org/docs.html#operation/get-search-manga
> This is the normal search endpoint, and Dex decided that when a chapter is uploaded for a manga it doesn't actually affect the update date for a manga (only manga info changes that information) so it needs to use this endpoint
> https://api.mangadex.org/docs.html#operation/get-chapter
> deedupe, and mention that no other filter can be used during..

Emm but https://mangadex.org/titles/latest/ us using https://api.mangadex.org/chapter?limit=30&offset=0&translatedLanguage[]=en&order[publishAt]=desc shouldn't latest also use this?

**Comment by arkon** [comment]
Isn't that what he said?

**Comment by FourTOne5** [comment]
Seems like I went blind there for a sec

**Comment by CarlosEsco** [comment]
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/8018
and
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/8017

**Comment by curche** [comment]
Looking at the screenshot the title at fault looks to be having an MU ID 64340 which points to this recently added(?) [manga](https://api.mangadex.org/manga/2e7ff32f-67d2-4f1c-896a-ddb60fca564d)
Checking with other manga, it looks like the description tag is at fault

the description tag: `"description":[]`
what tachi expects: `val description: Map<String, String>`
(Referring to the [MangaDto.kt](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/b495e6013a7e7a768c4520cfff831385732cd50c/src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/dto/MangaDto.kt#L44))

Could have other things at fault as well but nothing else caught our (mine or @nar1n) eyes

**Comment by arkon** [comment]
Reopening this for now since MD has no fix planned.

**Comment by arkon** [comment]
For the record:

![Screenshot_20210708-140708_Discord.png](https://user-images.githubusercontent.com/4098258/124970395-d8ab0400-dff5-11eb-95e6-fa70cb9393c0.png)

**Comment by lenrik1589** [comment]
some manga must come with adequate data, because in english source, if categories "Safe" "Suggestive" and "Erotica" are enabled, browse loads just fine, but as soon as "Pornographic" category is enabled it trips on the same place
w/o hentai 
![Screenshot_2021-07-09-04-20-10-969_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/48890625/125009527-5d853480-e06d-11eb-92b4-53524c095f5a.jpg)
with 
![Screenshot_2021-07-09-04-08-13-901_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/48890625/125009616-8b6a7900-e06d-11eb-8735-a7d031fcbd19.jpg)
w/o hentai, but japanese (don't ask me why the same titles?)
![Screenshot_2021-07-09-04-26-08-721_eu kanade tachiyomi debug](https://user-images.githubusercontent.com/48890625/125009738-ccfb2400-e06d-11eb-9324-ddad0369f131.jpg)
with hentai, same as in english (even the offset and `mu` thingie)

*And as auch, i propose a workaround for now*:
***just don't use "Pornographic" setting for any language***
but there might be something more clever
