### ISSUE TITLE
Nova fonte

### ISSUE THREAD

**Issue by Jefferson24323** [tachiyomiorg/tachiyomi-extensions#8787]
### Source name

Unionleitor

### Source link

https://unionleitor.xyz/index.html

### Language

Português e inglês

### Other details

I don't know if I had already put it on tachiyomi but it's there, it's a great site that I was recommended 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [X] I will fill out all of the requested information in this form.

**Comment by alessandrojean** [comment]
The website API doesn't provide a way to correctly separate the manga from each language, and some images aren't loading. Besides that, it looks like a lot of their titles are not active or being updated constantly.

The website is also a copycat of Union Mangás, which could cause confusion on the users because UM extension was removed and will not come back.
