### ISSUE TITLE
Lector Manga: chapter images do not load

### ISSUE THREAD

**Issue by Mtkmanjaro** [tachiyomiorg/tachiyomi-extensions#8859]
Tachiyomi version 0 .12 .1 (67)

Android  version 11

device redmi note 5+

Lectormanga versión 1. 2 .19

to reproduce the issue: 
open any manga from lectormanga you will get a black screen with the word retry 
expected behavior: load the manga successfully

additional information: 

i checked lectormanga website is online and working well, i checked the web view feature of tachiyomi and also is working well for lectormanga, i search in the issue list and i can't find nothing about this, two pull requests were done by @clouddark75 and then merge  regarding to this #8843 and this #8851 but after the update of the extension two times the issue still persist

**Comment by german2611** [comment]
The download and chapter view with the application doesn't work but if you go to webview and select the chapter does work
![photo4995021895980132623](https://user-images.githubusercontent.com/53231045/131202175-417550d4-59bf-41f1-9d8f-39a532f8b5a3.jpg)
![photo4995021895980132623](https://user-images.githubusercontent.com/53231045/131202177-f2c6223a-213a-4766-8c83-0b48d0d3eb06.jpg)

**Comment by Clouddark75** [comment]
> The site is doing some strange proxy stuff with its reader, whoever's taking this should consider using the response document's javascript to retreive image urls instead.

They kinda have started to block any outsider activity from the page itself probably asking for some access before loading them, and my knowledge for this isn't good enough for fixing it. They probably could be using Cloudflare proxy for it (but this is just my assumption) to try to stop segregators sites. Is funny because TMO (TuMangaOnline) main page kinda got the same, but something is different. But yah, lots of websites that where using their images URLs can't load them because of that.

**Comment by Shigani24** [comment]
@Clouddark75 So, there's no solution? 😔

**Comment by Mtkmanjaro** [comment]
it's depends if someone skilled enough want to take the job like @arkon

**Comment by edgarMejia** [comment]
> it's depends if someone skilled enough want to take the job like @arkon

Por favor deja de etiquetar a colaboradores, si el quisiera hacerlo o tuviese tiempo de hacerlo ya habria tomado esto.
