### ISSUE TITLE
Mad Scientistss

### ISSUE THREAD

**Issue by iitodi** [tachiyomiorg/tachiyomi-extensions#9271]
### Source name

Mad scientistss

### Source link

https://mad-scientistss.blogspot.com/?m=1

### Language

Arabic

### Other details

Please can you add this to tachiyomi 🙁🙁🙁

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a title with source name.
- [X] I have checked that the extension does not already exist on the [website extensions list](https://tachiyomi.org/extensions/) or the app.
- [X] I have checked that the extension does not already exist by searching the [GitHub repository](https://github.com/tachiyomiorg/tachiyomi-extensions/) and verified it does not appear in the code base.
- [x] I will fill out all of the requested information in this form.

**Comment by arkon** [comment]
Follow the instructions next time. There's already closed issues about this.

**Comment by Riztard** [comment]
> Follow the instructions next time. There's already closed issues about this.

wasnt it closed because of old request?

**Comment by arkon** [comment]
Maybe, kek

I thought we don't add Blogspot sites though.

**Comment by alessandrojean** [comment]
It's a blog website without a proper structure, it doesn't even look to have a manga details page, so it can be closed.

**Comment by Riztard** [comment]
i think it was bugged or something previously, because now it loads manga detail page properly

**Comment by shipoxx** [comment]
@Riztard 

Please close this request because the scan team retired some time ago and blog has been deleted.

**Comment by shipoxx** [comment]
> Maybe, kek
> 
> I thought we don't add Blogspot sites though.

I apologize for bothering you, but I am curious about requests about Blogger. Are these requests taken seriously? I mean, has a blogger been added before? Because I believe that there should be a policy regarding this matter, as long as a site is not professional (doesn't have a domain), it should not be taken into consideration for several reasons, including that anyone can create a blog and request to add it, and there will be hundreds of them and do not forget the template/theme, which is difficult to do. Sorry for bringing up a topic but I'm just curious, thank you.

**Comment by Riztard** [comment]
if it has proper page i think its ok

**Comment by arkon** [comment]
If it's structured enough, it's fine. Blogspot sites just generally aren't, but they could be.
