### ISSUE TITLE
Tapas "No pages found" / WebView cookies not saved

### ISSUE THREAD

**Issue by M-smith66** [tachiyomiorg/tachiyomi-extensions#9945]
### Source information

Tapas 1.2.13

### Steps to reproduce

1. Navigate to Browse -> Sources -> Tapas -> Globe Symbol / Open in WebView
2. Login
3. Force stop / Restart Tachiyomi
4. Open any pay-walled chapter which one owns. 

### Expected behavior

Chapter should display.

### Actual behavior

Only free chapters display properly. Purchased/pay-walled chapters fail to open/display, with an error reading "No pages found." 

When opening the WebView, it requires you to login each time, so it appears not to retain the cookie(s)/login information. Other extensions, like Tappytoon, work properly and it's WebView retains the logged-in state.

### Tachiyomi version

0.12.3-3977

### Android version

10

### Other details

App version: 0.12.3-3977 (standard, 430ff8019, 71, 2021-11-20T21:08Z)
Android version: 10 (SDK 29)
Android build ID: QP1A.190711.020.G965U1UES9FUG2
Device brand: samsung
Device manufacturer: samsung
Device name: star2qlteue
Device model: SM-G965U1
Device product name: star2qlteue

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[0.12.3](https://github.com/tachiyomiorg/tachiyomi/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] I have tried the [troubleshooting guide](https://tachiyomi.org/help/guides/troubleshooting/).
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/tachiyomiorg/tachiyomi/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

**Comment by ObserverOfTime** [comment]
The Tappytoon extension uses the API after grabbing the token from the frontend.

The Tapas extension can't use the API because the source doesn't store the token.
Instead, it reuses the cookies from the WebView when scraping the frontend.
Or at least, it's supposed to. Maybe it's failing to load them for some reason.

**Comment by alexporth** [comment]
For me you don't even need to exist the app. Three out of four times the login doesn't seem to stick. The time when it does work it is forgotten upon exiting the web view.

**Comment by cecoates** [comment]
Experiencing same issue.

This has also caused previously downloaded/paid for issues to become unavailable too, since "locked" items are hidden from view now.

Checked Android file system, and those files are there, but because of the above authentication issue Tachiyomi removed them from the library view. I don't believe Tachiyomi has any way to "relink" these items, unfortunately.

I thought previously it would display the titles of locked content but just not let you view them until you logged in (and paid for it). Is it possible to return to that setup?

**Comment by ObserverOfTime** [comment]
> since "locked" items are hidden from view now.

There's a setting for that.
https://github.com/tachiyomiorg/tachiyomi-extensions/blob/b7739ce48737111cd094c1f1964cf3361da46080/src/en/tapastic/src/eu/kanade/tachiyomi/extension/en/tapastic/Tapastic.kt#L109

**Comment by cecoates** [comment]
I already had that setting enabled, but "Show lock icon" was toggled off (maybe that setting was added/reset during one of the updates?) Toggling it to "on" means I can now see the lists.

![Screenshot 2021-12-03 00 10 30](https://user-images.githubusercontent.com/10121835/144554637-08bfb496-383b-4b67-81b4-423e02073cc7.png)

Still having the problem where I can't login/remain logged in so can't download new issues I've unlocked, but now I can see the old ones again. Thanks!

**Comment by hadi-susanto** [comment]
Experience same issues, 
1. Login to tapas in webview
2. Able to read purchased chapter
3. Back to reader, chapter list, refresh
4. Still show padlock icon, unable to read
5. Back to webview, atatus logged out

**Comment by yakau** [comment]
I believe that this can be closed.

The issue appears to have been resolved. I run Tachiyomi on two devices and Tapas has resumed working on both since I tried 20 minutes ago.

I suspect that whatever Tapas did to break the credentials on the m.tapas.io (mobile version of the site) was unintentional and they've fixed it.

Is the Tapas extension login working for all of you too?

**Comment by hadi-susanto** [comment]
issues solved, it seems tapas have gone wild a moment, can back to tachiyomi again for reading

**Comment by M-smith66** [comment]
It does appear to be fixed now, without my having updated anything.
